@startuml
' Syntax here: http://plantuml.com/sequence-diagram
' Sequence diagram showing calls from the FE to the various
' services associated with the healthbot

title Coronavirus-chatbot sequence diagram

skinparam shadowing false
skinparam roundcorner 20

' Definition of participants
actor user  #981b1e
entity browser #205493
control "healthbot service" as healthbot #7FBA00
control "va.gov" as vagov #112e51
boundary "VA network boundary"
control "vets-api" as vetsapi #112e51

autonumber
== Initiation/handshake ==
user -[#black]> browser: Click chatbot page link
browser -[#green]> vagov: GET va.gov/coronavirus-chatbot
vagov --[#green]> browser: initial page
browser -[#blue]> vetsapi: POST api.va.gov/v0/coronavirus_chatbot/tokens
vetsapi -[#orange]> healthbot: POST directline.botframework.com/\nv3/directline/tokens/generate
healthbot --[#orange]> vetsapi: response with token
vetsapi --[#blue]> browser: response with token
browser -[#orange]> healthbot: POST directline.botframework.com/\nv3/directline/conversations
healthbot --[#orange]> browser: response to initiate chat

== Chat ==
user -[#black]> browser: Ask first question
browser -[#orange]> healthbot: First question
healthbot --[#orange]> browser: First answer
...conversation continues...
user -[#black]> browser: Ask last question
browser -[#orange]> healthbot: Last question
healthbot --[#orange]> browser: Last answer
user -[#black]> browser: Click to find nearby VA locations
browser -[#green]> vagov: GET va.gov/find-locations/

legend center
    |Color| Type |
    |<#green>| Unauthenticated GET requests|
    |<#blue> | Unauthenticated POST requests|
    |<#red>| Authenticated GET requests|
    |<#orange>| Authenticated POST requests|
endlegend


@enduml
