name: Setup Environment for Large Repository

# Pre-install steps for GitHub Copilot in va.gov-team repository
# This configures Git LFS and optimizes the environment for the large repository
# NOTE: Standard ubuntu-latest runners work well with sparse checkout for most tasks

steps:
  - name: Verify runner specifications
    run: |
      echo "=== GitHub Actions Runner Information ==="
      echo "✅ This repository (~35GB) works well with standard runners when using sparse checkout"
      echo "✅ Recommended: ubuntu-latest (2-core) for most tasks with sparse checkout"
      echo "⚠️  Use larger runners (ubuntu-4-cores-latest, ubuntu-8-cores-latest) only for full repository operations"
      echo "📝 Note: Larger runners may have longer queue times"
      echo ""
      echo "Current runner specs:"
      echo "CPU cores: $(nproc)"
      echo "Memory: $(free -h | awk '/^Mem:/ {print $2}')"
      echo "Disk space: $(df -h / | awk 'NR==2 {print $4 " available"}')"
      echo ""
      
  - name: Configure Git LFS for large files (when needed)
    run: |
      git lfs install
      echo "Git LFS configured successfully"
      echo "Note: Git LFS is mainly needed for workflows that handle large files"
      
  - name: Verify repository optimization
    run: |
      echo "=== Repository Size Check ==="
      du -sh . || echo "Unable to check repository size"
      echo ""
      echo "=== Available Disk Space ==="
      df -h
      echo ""
      echo "=== Git LFS Status ==="
      git lfs ls-files | head -5 || echo "No LFS files found"
      echo ""
      echo "=== Directory Structure ==="
      ls -la
      echo ""
      echo "✅ Environment optimized for large repository work"
      echo ""
      echo "💡 Tips:"
      echo "- Use sparse checkout to limit directories checked out"
      echo "- Standard ubuntu-latest runners work well with sparse checkout"
      echo "- Monitor disk space during operations"
      echo "- Use larger runners only when full repository checkout is needed"
      
  - name: Setup Ruby environment (if needed)
    run: |
      ruby --version || echo "Ruby not available"
      if command -v ruby >/dev/null 2>&1; then
        echo "Ruby is available for validation scripts"
        if [ -f "scripts/manifest/validate_teams.rb" ]; then
          echo "✅ Team validation script found"
        else
          echo "⚠️ Team validation script not found in current checkout"
        fi
      fi
      
  - name: Setup Node.js environment (if needed)
    run: |
      node --version || echo "Node.js not available"
      npm --version || echo "npm not available"
      
  - name: Verify required directories
    run: |
      echo "Checking for required directories in sparse checkout:"
      for dir in ".github/workflows" "scripts" "teams" "products"; do
        if [ -d "$dir" ]; then
          echo "✅ $dir - available"
        else
          echo "⚠️ $dir - not available in current checkout"
        fi
      done
