@startuml

title Chatbot content process
skinparam ConditionEndStyle hline

start

if (Content change type?) then (FAQ text)
  #lightblue:Update FAQ text on VA.gov;
  if (Change to logic?) then (yes)
    #pink:repeat :Work with content team on new logic;
      'Update dev scenario;
      #lightgreen:Review logic in dev;
    repeat while (content in dev is good?) is (no)
  else (no)
      #lightgreen:repeat :Update chatbot-messages.md\npush to master;
        #yellow:CI to validate format, generate JS output;
        #pink:Upload js to healthbot dev environment;
        #pink:Check content in dev;
      repeat while (content is dev is good?) is (no)
      ->yes;
  endif
  #pink:Change "Last Updated Date" in vagov-content;
else (New CDC scenario)
  #pink:repeat :Pull CDC scenarios and localization file from git\nimport into dev;
  #lightgreen:Review new scenario in dev;
  repeat while (content in dev is good?) is (no)
endif

repeat

  repeat
    #pink:Upload new CDC localization file to staging;
    #pink:Trigger CI: staging promotion (1.0.1);
    #orange:Download scenarios from dev
    Filter scenarios
    commit results to master
    tag master 1.0.1
    upload scenario to staging
    run smoke test
    push git changes to remote;
    #lightgreen:Check content in staging;
    backward:fix issue;
  repeat while (content in staging is good?) is (no)
  ->yes;

  #pink:Upload new CDC localization file to prod;
  #pink:Trigger CI: prod promotion (1.0.1);
  #orange:Grab tagged ref from git
  add tag 1.0.1-release
  upload scenario to prod
  run smoke test
  push git changes to remote;
  #lightgreen:Check content in production;
  backward:fix issue;
repeat while (content in prod is good?) is (no)
->yes;

end

legend center
    |Color| Type |
    |<#lightblue> | VA stakeholders |
    |<#lightgreen>| Chatbot content team|
    |<#pink>| Engineering team|
    |<#orange>| CI - manually triggered|
    |<#yellow>| CI - automated|
endlegend

@enduml
