@startuml

title Chatbot content process
scale 0.7
skinparam ConditionEndStyle hline

start

#lightblue:Update FAQ text on VA.gov;
if (Change to logic / new question?) then (yes)
repeat
#pink:Work with content team on new logic;
#lightgreen:Check content in dev;
repeat while (content in dev is good?) is (no)
->yes;
else (no)
endif
repeat
repeat
repeat
#lightgreen:Update markdown_answers.md\npush to master;
#yellow:CI to validate format, generate JS output;
#pink:Upload js to healthbot dev environment;
#lightgreen:Check content in dev;
repeat while (content is dev is good?) is (no)
->yes;
#pink:Trigger jenkins staging promotion (1.0.1);
#orange:Download scenarios from dev
Filter scenarios
upload scenario to staging
run smoke test
commit results to master
tag master 1.0.1-RC1;
#lightblue:Check content in staging;
repeat while (content in staging is good?) is (no)
->yes;
#pink:Trigger jenkins prod promotion (1.0.1-RC1);
#orange:Grab tagged ref from git
upload scenario to prod
run smoke test
tag master 1.0.1;
#lightgreen:Check content in production;
repeat while (content in prod is good?) is (no)
->yes;
end

legend center
    |Color| Type |
    |<#lightblue> | Outside team|
    |<#lightgreen>| Chatbot content team|
    |<#pink>| Engineering team|
    |<#orange>| CI - manually triggered|
    |<#yellow>| CI - automated|
endlegend

@enduml
