
name: Disability Benefits - Spike Template
description: Spikes for Disability Benefits Team 
labels: ["disability", "disability-benefits", "needs-refinement"]
projects: 
- department-of-veterans-affairs/1660
type: Task

body:
- type: markdown
  attributes:
    value: |
      Use clear, simple language and action verbs to describe the work. Avoid acronyms and jargon.
- type: textarea
  attributes:
    label: Background
    description: Describe the scope of this research, background context, why it matters, and dependencies.
- type: textarea
  attributes: 
    label: Research goals
    description: What questions should this research answer?
- type: markdown
  attributes:
    value: |
      ## Evidence
      Document links and notes from this research that inform the conclusions below.
  
      ## Conclusions
      What did you learn? Answer the questions outlined in the Goal section above. 
  
      ## Next Steps
      What work do you recommend based on your conclusions? Link to any issues.
- type: checkboxes
  attributes:
    label: Refinement Checklist! 
    description: Make this ticket ready to work
    options: 
      - label: Added description, tasks, and acceptance criteria
      - label: Added estimate
      - label: Labeled with Practice Area (engineer, design, product, data science)
      - label: Labeled with issue type and characteristics of the ticket (bug, accessibility, request, discovery, documentation, research, content, ux testing, front-end, back-end, datadog, etc.)
      - label: Added any other relevant project fields (team, OCTO priority...)
      - label: Added an Epic or Super Epic
