name: "Identity Product Support"
description: "For general Identity support request"
labels: "Identity, identity-product-support"
assignees: jimcconnelly, kingbmike
body:
- type: markdown
  attributes:
    value: |
      # Identity Product Support Request

      This is a GitHub issue template for users and teams who need product support services from the [Identity team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity). Please provide the information needed for the issue type you are requesting support for. For “other” please provide additional details. You may view Identity teams documentation for all of our products and services [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products). For engineering support, use our [engineer issue template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joeniquette&labels=Identity%2C+identity-engineer-support&projects=&template=1dentity-engineer-support.md&title=) instead.

      ## To properly assist with your issue, please complete the following:

      - [ ] Complete this issue template
      - [ ] Provide your name and email address
      - [ ] Provide your team’s name
      - [ ] Select issue type (for “other” stop here and provide details)
        - [ ] [Data Request](#data)
        - [ ] [Sign-in Service Integration](#sis)
        - [ ] [Other](#other)
      - [ ] Complete tasks for your issue type
      - [ ] Add additional details (optional)
      - [ ] Complete the [post Identity team support survey](https://dj540s05.optimalworkshop.com/questions/52low0ey) before closing this ticket

      <details>
        <summary>
          <h3 id="data">Data request</h3>
        </summary>
        For data requests provide the following additional details. As a reminder please don’t include any Personal Identifying Information (PII) or Protected Health Information (PHI). 
        <ul>
          <li>What data do you need pulled? Please don’t include any Personal Identifying Information (PII)</li>
          <li>Is this sensitive data that requires special permissions?</li>
        </ul>
      </details>
      <details>
        <summary>
          <h3 id="data">Sign-in Service integration</h3>
        </summary>
        <p>
          We maintain a <a href="https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service">Sign-in Service overview</a> as well as <a href="https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs">engineering documentation</a> in the va-gov-team GitHub repository. To begin onboarding or register a Client or Service Configuration, continue reading.
        </p>
        <h4>Begin onboarding</h4>
        <ol>
          <li>Provide the first and last name of the primary point of contact</li>
          <li>Provide an email address for the primary point of contact</li>
        </ol>
        <h4>Onboarding questionnaire</h4>
        <p>When filling out the onboarding questionnaire for Sign-in Service integration answer the following questions in the "Provide additional details" section.</p>
        <ol>
          <li>
            Does your application interact with end users, API’s or both?<br />
            <ul>
              <li><em>If end users interact with your application, you will most likely need to <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/configuration/client_config.md">configure your integration as a client application</a>.</em></li>
              <li><em>If end users don’t interact with your application, your integration will likely need to be <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/configuration/service_account.md">configured as a service account</a>.</em></li>
          </li>
          <li>
            Do you need to use our <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Unified%20Sign%20In%20Pages/README.md">Unified Sign-in Page</a> (USiP)?
          </li>
          <li>
            If your application is used by end users, is it used in a web browser?<br />
            <ul>
              <li><em>If so, your application will need <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/auth_flows/cookie_oauth.md">cookie-based authentication</a>.</em></li>
              <li>If not, your application will need to <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/auth_flows/api_oauth.md">authenticate via API</a>.</em></li>
            </ul>
          </li>
          <li>
            Is your authentication facilitated by a frontend or a secure backend?<br />
            <ul>
              <li><em>If frontend reference the appropriate authentication guide in Step #3 and complete the step for PKCE authentication.</em></li>
              <li><em>If backend, reference the authentication guide, but register a public certificate for <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/auth_flows/private_key_jwt.md">private key JWT authentication</a>.</em></li>
            </ul>
          </li>
        </ol>
        <h4>Client configuration</h4>
        <ol>
          <li>Is the application used in a web browser or mobile app?</li>
          <li>Will your application be using our <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Unified%20Sign%20In%20Pages/README.md">Unified Sign-in Page</a>?</li>
          <li>Briefly describe your application in the additional details section</li>
        </ol>
        <h4>Service configuration</h4>
        <ol>
          <li>Briefly describe your application in the additional details section</li>
        </ol>
      </details>
      <details>
        <summary>
          <h3 id="other">Other</h3>
        </summary>
        For "Other" provide as much additional details as possible. As a reminder please don’t include any Personal Identifying Information (PII) or Protected Health Information (PHI).
      </details>
- type: input
  id: name
  attributes:
    label: Provide your name
- type: input
  id: email
  attributes:
    label: Provide your email address
  validations:
    required: true
- type: input
  id: team_name
  attributes:
    label: Provide your team’s name
- type: dropdown
  id: issue_type
  attributes:
    label: Select issue type (for "other" stop here and provide details)
    options:
      - Select an issue type
      - Data Request
      - Sign-in Service Integration
      - Other
    multiple: false
    default: 0
  validations:
    required: true
- type: textarea
  id: details
  attributes:
    id: additional-details
    label: Provide additional details
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ## **Additional information**

      - The identity team maintains [office hours](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service/Support) for both frontend and backend engineers.
      - You may reach out to an identity team member on the `#vsp-identity` [slack channel](https://dsva.slack.com/archives/CSFV4QTKN) on the Office of the CTO @ va slack workspace.
      - Please review the `#vsp-identity` slack channel [canvas] to reference information about the identity team.
