name: Accessibility Testing Update
description: Complete required accessibility testing prior to your Staging review.
title: "Accessibility Testing for [Team Name, Product Name, Feature Name]"
labels: ["a11y-testing"]
assignees:
  - jasonday
body:
  - type: markdown
    attributes:
      value: |
        ## 1. Introduction
  - type: markdown
    attributes:
      value: |
        This issue template will help walk you through [required and recommended accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) and will generate a testing artifact you can submit as part of your staging review. Try to resolve as many issues as you're able to before your staging review, and update this artifact with that progress. Log any issues you find (see #5 Next Steps).
        
        ### Why we ask VFS teams to do accessibility testing
        The more you test and fix issues before your staging review, the less likely we are to find launch-blocking issues. This artifact helps document your accessibility testing efforts and any issues you found along the way. It also helps us understand your product better before we do our review.
  - type: markdown
    attributes:
      value: |
        ## 2. Before you begin

        The Required and Recommended checklists below are based on WCAG 2.2 and the [VA.gov Accessibility Standards](https://depo-platform-documentation.scrollhelp.site/accessibility/va-gov-accessibility-standards).

        Complete all required checks and as many recommended checks as you can. If you can't complete a required check, please explain why in the comments.

        Checking a checklist item indicates that your product has passed that check. If you find an issue while performing a check, do not mark it as complete. Instead, log the issue (see #5 Next Steps) and leave the check unmarked. If the check is not applicable to your product, mark it as passed.
  - type: checkboxes
    id: product-info
    attributes:
      label: Product information
      options:
        - label: Team name, product name, and feature name have been added to the title of this issue.
          required: true
        - label: Team label, product label and feature label (if applicable) have been added to this issue.
          required: true
  - type: markdown
    attributes:
      value: |
        ## 3. Required Testing
  - type: checkboxes
    id: automated-checks
    attributes:
      label: Automated testing
      description: AXE has been run against every page in your flow, including page variations, interactive states of content, etc. [Learn more about testing with axe](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-AutomatedtestingwithaxebyDequeaxe)
      options:
        - label: <strong>AXE has been executed for every page. (Automated-001)</strong> <br/>AXE has been run against every page in your flow, including page variations, interactive states of content, etc.
        - label: <strong>AXE has been integrated in end to end testing. (Automated-002)</strong> <br/>End to end testing with Cypress or other libraries includes AXE scanning. <br/>[Learn more about integrating axe in end-to-end testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress).

  - type: textarea
    id: automated-testing-notes
    attributes:
      label: Automated testing output
      description: Please add the results of your automated testing. Provide screenshots of the AXE results organized by url or name of screen tested. If there's a ticket or results from E2E testing, please link to that here. 
      value: |
        Axe results screenshots or link to ticket:

        E2E testing results or link to ticket:

  - type: checkboxes
    id: images-checks
    attributes:
      label: Images
      description: Ensure all non-text content is accessible.
      options:
        - label: <strong>Meaningful descriptions are provided for informative images (WEB-111-001).</strong> <br/>All informative images have a text alternative that is meaningful and serves the equivalent purpose.

  - type: checkboxes
    id: audio-video-checks
    attributes:
      label: Audio & video
      description: Ensure multimedia content is perceivable.
      options:
        - label: <strong>Captions are provided for all prerecorded videos (WEB-122).</strong> <br/>Prerecorded videos include synchronized captions for dialogue, sound effects, and relevant audio.
        - label: <strong>Transcripts or audio descriptions are included for videos (WEB-123).</strong> <br/>For non-live video, a full descriptive transcript or an audio description is provided.
        - label: <strong>Auto-playing audio can be paused or has volume controls (WEB-142).</strong> <br/>Audio that plays automatically for more than 3 seconds can be paused OR has an independent volume control.

  - type: checkboxes
    id: structure-semantics-checks
    attributes:
      label: Structure & semantics
      description: Ensure content structure and semantics are accessible.
      options:
        - label: <strong>Headings match the content hierarchy and use proper HTML tags (WEB-131-001).</strong> <br/>Headings accurately reflect content hierarchy and are semantically marked for assistive technology.
        - label: <strong>Each page has a unique, descriptive title (WEB-242).</strong> <br/>Each web page, or screen, has a unique and descriptive title reflecting its purpose.
        - label: <strong>Headings are descriptive (WEB-246-001).</strong> <br/>Heading text accurately describes the topic or purpose of the content that follows it.

  - type: checkboxes
    id: color-contrast-sensory-checks
    attributes:
      label: Color, contrast, & sensory
      description: Ensure information is not conveyed by color alone and meets contrast requirements.
      options:
        - label: <strong>Instructions don't rely only on color, shape, size, or sound (WEB-133).</strong> <br/>Instructions for operating content and cues for identifying content do not rely exclusively on color, shape, size, position, or sound.
        - label: <strong>Information is not communicated by color alone (WEB-141).</strong> <br/>Color is never the sole visual means of conveying information, indicating actions, prompting responses, or distinguishing elements.
        - label: <strong>Text has sufficient contrast against its background (WEB-143).</strong> <br/>Text and images of text have a contrast ratio of at least 4.5:1 and large-scale text and images of large-scale text have a contrast ratio of at least 3:1.
        - label: <strong>Interactive elements are visually distinct from surroundings (WEB-1411-001).</strong> <br/>The visual presentation of all active user interface components achieves a 3:1 contrast ratio against adjacent colors.
        - label: <strong>Important graphics and icons have sufficient contrast (WEB-1411-002).</strong> <br/>Graphical objects essential for understanding content maintain a 3:1 contrast ratio against adjacent colors.

  - type: checkboxes
    id: layout-responsiveness-checks
    attributes:
      label: Layout & responsiveness
      description: Ensure content adapts to different screen sizes and zoom levels.
      options:
        - label: <strong>Text can be enlarged to 200% without breaking the page (WEB-144).</strong> <br/>Text can be resized up to 200% without page content disappearing or losing functionality.
        - label: <strong>No images of text (WEB-145).</strong> <br/>Images of text are not used when the same presentation can be made with native HTML/CSS. Logos and branding are excluded.
        - label: <strong>Content fits on small screens without horizontal scrolling (WEB-1410).</strong> <br/>Content reflows to a single-dimension scroll at 320x256 CSS pixels and larger, unless horizontal scrolling is essential for meaning or function.

  - type: checkboxes
    id: keyboard-focus-checks
    attributes:
      label: Keyboard & focus
      description: Ensure all functionality is operable via keyboard and focus is visible.
      options:
        - label: <strong>All functionality works with keyboard only (WEB-211).</strong> <br/>All interactive elements and features can be accessed and operated using only a keyboard.
        - label: <strong>No keyboard trap (WEB-212).</strong> <br/>Keyboard focus can always move away from any element using standard keys. If the method requires more than ESC, Arrow Keys, or Tab, the user must be informed of the method.
        - label: <strong>Every focusable element has a visible focus indicator (WEB-247).</strong> <br/>All interactive elements show a visible outline or indicator when receiving keyboard focus.

  - type: checkboxes
    id: timing-interruptions-checks
    attributes:
      label: Timing & interruptions
      description: Ensure time limits and moving content do not interfere with accessibility.
      options:
        - label: <strong>Automatically moving content can be paused or stopped (WEB-222).</strong> <br/>All moving, blinking, scrolling, or auto-updating content provides mechanisms to pause, stop, hide, or control its frequency if it starts automatically and lasts over 5 seconds.

  - type: checkboxes
    id: navigation-consistency-checks
    attributes:
      label: Navigation & consistency
      description: Ensure navigation is consistent and users can bypass repeated content.
      options:
        - label: <strong>Users can skip repeated content like headers and navigation (WEB-241).</strong> <br/>A mechanism is provided to bypass repeated blocks of content (e.g., navigation, headers) on multiple webpages.

  - type: checkboxes
    id: forms-controls-checks
    attributes:
      label: Forms & interactive controls
      description: Ensure forms are accessible and provide clear instructions.
      options:
        - label: <strong>Form labels clearly describe what to enter (WEB-246-002).</strong> <br/>Labels describe the purpose or function of form fields and controls.
        - label: <strong>Form fields have visible labels (WEB-332-001).</strong> <br/>Visible labels or instructions are available for all inputs and input groupings.
        - label: <strong>Fields with specific formats include instructions (WEB-332-002).</strong> <br/>Form fields that require specific formats provide instructions or examples.
        - label: <strong>Required or optional fields are clearly marked (WEB-332-003).</strong> <br/>All required fields are identified with visible labels or instructions OR all optional fields are identified with visible labels or instructions.
        - label: <strong>Error messages explain how to fix the problem (WEB-333).</strong> <br/>Users are provided with clear suggestions for correcting input errors, unless doing so would compromise security or the content's purpose.
        - label: <strong>Links navigate to pages; buttons perform actions (WEB-412-003).</strong> <br/>User interface elements defined as links are used for navigation and elements defined as buttons perform in-page actions or submit forms.
  - type: markdown
    attributes:
      value: |
        ## 5. Next steps
  - type: checkboxes
    id: add-link
    attributes:
      label: Add link to Collaboration Cycle ticket
      description: 
      options:
        - label: Add a link to your completed accessibility testing ticket to the staging review artifacts section of your Collaboration Cycle ticket. You can close this ticket after you complete your staging review.

  - type: checkboxes
    id: logged
    attributes:
      label: Report identified issues
      description:  For any issues identified during your testing, please report them as part of your staging review.
      options:
        - label: Log the issue using the [Accessibility issue template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?template=a11y-issue.yaml&assignees=jasonday&labels=a11y-testing&title=A11y+testing+finding%3A+%5Bshort+description%5D) filling in as much information as you are able.
        - label: Assign to `jasonday` and add the `a11y-testing` label.
        - label: Add the created issue to the Collaboration Cycle milestone found in your collab cycle ticket.
        - label: Provide a link to each issue logged in this accessibility testing artifact's comments
