name: Accessibility Testing Update
description: Complete required accessibility testing prior to your Staging review.
title: "Accessibility Testing for [Team Name, Product Name, Feature Name]"
labels: ["a11y-testing"]
assignees:
  - jasonday
body:
  - type: markdown
    attributes:
      value: |
        ## 1. Introduction
  - type: markdown
    attributes:
      value: |
        This issue template will help walk you through [required and recommended accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) and will generate a testing artifact you can submit as part of your staging review. Try to resolve as many issues as you're able to before your staging review, and update this artifact with that progress. Log any issues you find (see 4. Next Steps).
        
        ### Why we ask VFS teams to do accessibility testing
        The more you test and fix issues before your staging review, the less likely we are to find launch-blocking issues. This artifact helps document your accessibility testing efforts and any issues you found along the way. It also helps us understand your product better before we do our review.
  - type: markdown
    attributes:
      value: |
        ## 2. Before you begin

        The Required and Recommended checklists below are based on WCAG 2.2 and the [VA.gov Accessibility Standards](https://depo-platform-documentation.scrollhelp.site/accessibility/va-gov-accessibility-standards).

        Complete all required checks and as many recommended checks as you can. If you can't complete a required check, please explain why as a comment on this ticket.

        Checking a checklist item indicates that your product has passed that check. If you find an issue while performing a check, do not mark it as complete. Instead, log the issue (see 4. Next Steps) and leave the check unmarked. If the check is not applicable to your product, mark it as passed.
  - type: checkboxes
    id: product-info
    attributes:
      label: Product information
      options:
        - label: Team name, product name, and feature name have been added to the title of this issue.
          required: true
        - label: Team label, product label and feature label (if applicable) have been added to this issue.
          required: true
  - type: markdown
    attributes:
      value: |
        ## 3. Required Testing
  - type: checkboxes
    id: automated-checks
    attributes:
      label: Automated testing
      description: Automated testing verifies accessibility by running automated scans on every page and integrating those scans into end‑to‑end tests, ensuring issues are caught early and consistently. 
      options:
        - label: <strong>Axe Devtools has been run on every page. (Required)</strong> <br/>Axe DevTools has been run against every page in your flow, including page variations, interactive states of content, etc. (Automated-001) <br/> [Learn more about testing with Axe DevTools](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-AutomatedtestingwithaxebyDequeaxe)
        - label: <strong>Axe-core has been integrated in end to end testing. (Required) </strong> <br/>End to end testing with Cypress or other libraries includes Axe-core scanning. (Automated-002)<br/>[Learn more about integrating axe in end-to-end testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress).

  - type: textarea
    id: automated-testing-notes
    attributes:
      label: Automated testing output
      description: Please add the results of your automated testing. Provide screenshots of the AXE results organized by url or name of screen tested. If there's a ticket or results from E2E testing, please link to that here. 
      value: |
        Axe results screenshots or link to ticket:

        E2E testing results or link to ticket:

  - type: checkboxes
    id: images-checks
    attributes:
      label: Images
      description: Ensure all non-text content is accessible.
      options:
        - label: <strong>Meaningful descriptions are provided for informative images. (Required)</strong> <br/>All informative images have a text alternative that is meaningful and serves the equivalent purpose. (WEB-111-001)
        - label: <strong>No images of text. (Required)</strong> <br/>Images of text are not used when the same presentation can be made with native HTML/CSS. Logos and branding are excluded. (WEB-145)
        - label: <strong>Brief and detailed descriptions are provided for complex images.(Recommended)</strong><br/> Complex images (graphs, maps, charts) have both alt text and longer descriptions that together accurately convey all relevant information. (WEB-111-002)
        - label: <strong>Decorative images are hidden from screen readers. (Recommended)</strong><br/> All non-text content that is decorative, provides no contextual value, or is already defined by surrounding content is hidden from screen readers. (WEB-111-003)
        - label: <strong>Background images are not used for informative content. (Recommended)</strong><br/> CSS background images contain no meaningful content, or that content is available through other means. (WEB-111-004)
 
  - type: checkboxes
    id: audio-video-checks
    attributes:
      label: Audio & video
      description: Ensure multimedia content is perceivable.
      options:
        - label: <strong>Captions are provided for all prerecorded videos. (Required)</strong> <br/>Prerecorded videos include synchronized captions for dialogue, sound effects, and relevant audio. (WEB-122)
        - label: <strong>Transcripts or audio descriptions are included for videos. (Required)</strong> <br/>For non-live video, a full descriptive transcript or an audio description is provided. (WEB-123)
        - label: <strong>Auto-playing audio can be paused or has volume controls. (Required)</strong> <br/>Audio that plays automatically for more than 3 seconds can be paused OR has an independent volume control. (WEB-142)
        - label: <strong>Text transcripts are provided for audio and video-only content. (Recommended)</strong><br/>For audio-only and video-only media, a transcript is provided which provides the same information as presented in the original media content. (WEB-121)
        - label: <strong>Real-time captions are provided for live videos (Recommended)</strong><br/>Live video includes synchronized captions generated in real-time. (WEB-124)

  - type: checkboxes
    id: structure-semantics-checks
    attributes:
      label: Structure & semantics
      description: Ensure content structure and semantics are accessible.
      options:
        - label: <strong>Headings match the content hierarchy and use proper HTML tags. (Required)</strong> <br/>Headings accurately reflect content hierarchy and are semantically marked. (WEB-131-001)
        - label: <strong>Headings follow a logical order without skipping levels. (Required)</strong><br/>Heading levels follow a logical, sequential, hierarchy with no skipped heading levels. (WEB-131-002)
        - label: <strong>There is one H1 per page/screen. (Required)</strong></br/>A single H1 exists for every page or screen. (WEB-131-003)
        - label: <strong>Each page has a unique, descriptive title. (Required)</strong> <br/>Each web page, or screen, has a unique and descriptive title reflecting its purpose. (WEB-242)
        - label: <strong>Headings are descriptive. (Required)</strong> <br/>Heading text accurately describes the topic or purpose of the content that follows. (WEB-246-001)
        - label: <strong>Lists use proper list formatting. (Recommended)</strong><br/> All visually apparent lists are marked up using semantic list types. (WEB-131-004)
        - label: <strong>Content is organized into sections. (Recommended)</strong><br/> Where content is organized in sections, section headings are provided. (WEB-2410)
        - label: <strong>The page language is identified. (Recommended)</strong><br/> The `<html>` element includes a valid `lang` attribute specifying the page's primary language. (WEB-311)
        - label: <strong>Content in another language is identified. (Recommended)</strong><br/> Text in different languages from the page's primary language is marked with `lang` attributes. (WEB-312)

  - type: checkboxes
    id: color-contrast-sensory-checks
    attributes:
      label: Color, contrast, & sensory
      description: Ensure information is not conveyed by color alone and meets contrast requirements.
      options:
        - label: <strong>Instructions don't rely only on color, shape, size, or sound. (Required)</strong> <br/>Instructions and cues do not rely exclusively on sensory characteristics. (WEB-133)
        - label: <strong>Information is not communicated by color alone. (Required)</strong> <br/>Color is never the sole visual means of conveying information. (WEB-141)
        - label: <strong>Text has sufficient contrast against its background. (Required)</strong> <br/>Text and images of text have a contrast ratio of at least 4.5:1 and large-scale text and images of large-scale text have a contrast ratio of at least 3:1. (WEB-143)
        - label: <strong>Interactive elements are visually distinct from surroundings. (Required)</strong> <br/>Active user interface components achieve a 3:1 contrast ratio against adjacent colors. (WEB-1411-001)
        - label: <strong>Important graphics and icons have sufficient contrast. (Required)</strong> <br/>Essential graphical objects have a contrast ratio of at least 3:1 contrast. (WEB-1411-002)

  - type: checkboxes
    id: layout-responsiveness-checks
    attributes:
      label: Layout & responsiveness
      description: Ensure content adapts to different screen sizes and zoom levels.
      options:
        - label: <strong>Text can be enlarged to 200% without breaking the page. (Required)</strong> <br/>Text can be resized up to 200% without loss of content or functionality. (WEB-144)
        - label: <strong>Content fits on small screens without horizontal scrolling (Required).</strong> <br/> Content reflows to a single-dimension scroll at 320x256 CSS pixels and larger. (WEB-1410)
        - label: <strong>Content works in both portrait and landscape mode. (Recommended)</strong><br/>Content is viewable in portrait and landscape orientations unless essential otherwise. (WEB-134)
        - label: <strong>Text remains readable when spacing is adjusted. (Recommended)</strong><br/>No content or functionality may be lost when text is set to:line spacing of 1.5x font size, letter spacing at 0.12x font size, word spacing at 0.16x font size, and paragraph spacing 2x the font size and that styling does not prevent overrides. (WEB-1412)

  - type: checkboxes
    id: keyboard-focus-checks
    attributes:
      label: Keyboard & focus
      description: Ensure all functionality is operable via keyboard and focus is visible.
      options:
        - label: <strong>All functionality works with keyboard only. (Required)</strong> <br/>All interactive elements and features can be accessed and operated using only a keyboard. (WEB-211)
        - label: <strong>No keyboard trap. (Required)</strong> <br/>Keyboard focus can always move away from any element using standard keys. (WEB-212)
        - label: <strong>Every focusable element has a visible focus indicator. (Required)</strong> <br/>All interactive elements show a visible outline or indicator when receiving keyboard focus. (WEB-247)
        - label: <strong>Tab order follows a logical sequence. (Recommended)</strong><br/>Keyboard focus moves through interactive elements in a meaningful order. (WEB-243)
        - label: <strong>The element with focus is always visible. (Recommended)</strong><br/>The visible focus indicator is not completely obscured by other content. (WEB-2411)
        - label: <strong>Focusing on an element doesn't trigger unexpected changes. (Recommended)</strong><br/>Focusing an element does not trigger a change of context. (WEB-321)
        - label: <strong>Interacting with form fields doesn't trigger unexpected changes. (Recommended)</strong><br/> Changing form values does not automatically cause navigation or context changes. (WEB-322)

  - type: checkboxes
    id: timing-interruptions-checks
    attributes:
      label: Timing & interruptions
      description: Ensure time limits and moving content do not interfere with accessibility.
      options:
        - label: <strong>Automatically moving content can be paused or stopped. (Required)</strong> <br/>All moving, blinking, scrolling, or auto-updating content provides mechanisms to pause, stop, hide, or control its frequency if it starts automatically and lasts over 5 seconds. (WEB-222)

  - type: checkboxes
    id: navigation-consistency-checks
    attributes:
      label: Navigation & consistency
      description: Ensure navigation is consistent and users can bypass repeated content.
      options:
        - label: <strong>Users can skip repeated content like headers and navigation. (Required)</strong><br/>A mechanism is provided to bypass repeated blocks of content (e.g., navigation, headers) on multiple webpages such as a skip link, HTML5 landmarks, etc. (WEB-241)
        - label: <strong>Pages can be found in multiple ways. (Recommended)</strong><br/>Two or more mechanisms of finding a webpage are available, unless the page is accessed as part of a step in a process. (WEB-245)
        - label: <strong>Navigation structure is the same across pages. (Recommended)</strong><br/> Navigation menus maintain consistent order and structure across multiple pages. (WEB-323)
        - label: <strong>Help options appear in the same location on all pages. (Recommended)</strong><br/>Help mechanisms such as contact details, messaging, chat, or self-help options must be in the same relative order on all pages where the information is present. (WEB-326)

  - type: checkboxes
    id: forms-controls-checks
    attributes:
      label: Forms & interactive controls
      description: Ensure forms are accessible and provide clear instructions.
      options:
        - label: <strong>Form labels clearly describe what to enter. (Required)</strong> <br/>Labels describe the purpose or function of form fields and controls. (WEB-246-002).
        - label: <strong>Form fields have visible labels. (Required)</strong> <br/>Visible labels or instructions are available for all inputs and input groupings. (WEB-332-001)
        - label: <strong>Fields with specific formats include instructions. (Required)</strong> <br/>Form fields that require specific formats provide instructions or examples. (WEB-332-002).
        - label: <strong>Required or optional fields are clearly marked. (Required)</strong> <br/>All required fields are identified with visible labels or instructions OR all optional fields are identified with visible labels or instructions. (WEB-332-003)
        - label: <strong>Error messages explain how to fix the problem. (Required)</strong> <br/>Users are provided with clear suggestions for correcting input errors, unless doing so would compromise security or the content's purpose. (WEB-333)
        - label: <strong>Links navigate to pages; buttons perform actions. (Required)</strong> <br/>User interface elements defined as links are used for navigation and elements defined as buttons perform in-page actions or submit forms. (WEB-412-003)
        - label: <strong>Related form elements are grouped together. (Recommended)</strong><br/> Related form controls (e.g., radio buttons, checkboxes, multi-part text inputs) are semantically grouped to convey their relationships. (WEB-131-005)
        - label: <strong>Required fields are clearly marked with text and in code. (Recommended)</strong><br/>Required fields/controls are identified in text and programmatically. (WEB-131-007)
        - label: <strong>Links are descriptive. (Recommended)</strong><br/>Link text or its accessible name describes the link's destination or purpose. (WEB-244)
        - label: <strong>Error messages are provided and are clear. (Recommended)</strong><br/>Whenever an input error is detected, the user is informed of the error and how to correct the error. (WEB-331)
        
  - type: markdown
    attributes:
      value: |
        <br/>
        
        ## 4. Next steps
  - type: checkboxes
    id: add-link
    attributes:
      label: Add link to Collaboration Cycle ticket
      description: 
      options:
        - label: Add a link to your completed accessibility testing ticket to the staging review artifacts section of your Collaboration Cycle ticket. You can close this ticket after you complete your staging review.

  - type: checkboxes
    id: logged
    attributes:
      label: Report identified issues
      description:  "For any issues identified during your testing, please report them as part of your staging review. Note: the accessibility testing artifact should be completed when the product is ready for staging review (stable). If your team tracks issues in a different way, please provide that information as a comment on this ticket.
      options:
        - label: Log the issue using the [Accessibility issue template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?template=a11y-issue.yaml&assignees=jasonday&labels=a11y-testing&title=A11y+testing+finding%3A+%5Bshort+description%5D) filling in as much information as you are able.
        - label: Assign to `jasonday` and add the `a11y-testing` label.
        - label: Add the created issue to the Collaboration Cycle milestone found in your collab cycle ticket.
        - label: Provide a link to each issue logged in a comment on this ticket.
