name: "Accessibility Maintenance Audit"
description: "Create an epic for a maintenance a11y audit outside of the collaboration cycle"
title: "[Maintenance A11y Audit]: "
labels: ["epic, accessibility, a11y-testing, sitewide CAIA, sitewide accessibility"]
assignees: []
body:
- type: markdown
  attributes:
    value: "## Instructions for specialist"
- type: markdown
  attributes:
    value: |
      [Follow these instructions on how to conduct a maintenance audit](https://docs.google.com/document/d/1nrpUyjtbfMkVd8uxxSzEvLzBHOZbwTbw6g0gKbo2nJY/edit?usp=sharing)
- type: markdown
  attributes:
    value: "## Audit Details"
- type: textarea
  id: review
  attributes:
    label: Definition of done
    description: Provide a list of test users and any relevant instructions. [Link to VA a11y dashboard](https://docs.google.com/spreadsheets/d/1lgzMiZZ-0rBPDuB2gRupBAjsyF0WTe005VvEHYrMxww/edit?usp=sharing)
    value: |
      1. Review and acknowledge all issues added to this maintenance audit.
      2. Fix and/or document decisions made for all issues.
      3. A11y specialist will review documented decisions or validating fixes for all tickets.
      4. A11y specialist will update the product page on the VA a11y dashboard.
      5. A11y specialist will close this ticket.
- type: input
  id: auditor
  attributes:
    label: Auditor(s)
    description: The person or people conducting this audit
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Coverage of Testing"
- type: checkboxes
  id: automated
  attributes:
    label: Automated
    options:
      - label: Run axe checks on every page or unique state (required)
      - label: Run WAVE on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.
- type: checkboxes
  id: manual
  attributes:
    label: Manual
    options:
      - label: Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
      - label: Color blindness checks
      - label: Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
      - label: Keyboard navigation
- type: checkboxes
  id: screenreader
  attributes:
    label: Screen Reader
    options:
      - label: Windows, Chrome, JAWS 
      - label: iPhone, iOS Safari, VoiceOver 
- type: textarea
  id: other
  attributes:
    label: Other tests
    description: Provide a list of any other tests conducted
    value: |
      1. for example, Dragon Naturally Speaking on Chrome on Windows
      2.
      3.
      ...
- type: input
  id: sheet
  attributes:
    label: Audit sheet link
    description: Provide a link to any sheets or tools used for the audit; [you can use this complex audit google sheet](https://docs.google.com/spreadsheets/d/1QXwkudLtG8aX7g5NGuwW_CgNHEmvV59hPRCoQORlA7Q/edit?usp=sharing)
- type: markdown
  attributes:
    value: "## Staging URL and Credentials"
- type: input
  id: staging-link
  attributes:
    label: Staging or Production Link
    description: Consider linking to the first page of the tool or feature you're auditing 
- type: input
  id: prototypes
  attributes:
    label: Prototype Link
    description: Provide a link to any relevant prototypes
- type: textarea
  id: testusers
  attributes:
    label: Test Users
    description: Provide a list of test users and any relevant instructions
    value: |
      1.
      2.
      3.
      ...
- type: markdown
  attributes:
    value: "[Passwords for test users](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/a11y-audit.md#:~:text=user%2B%3F%3F%40gmail.com-,Passwords,-Footer)"
      
      
      
      
      
