name: "Research Support Ticket (ADE)"
description: "Request support for user research with Veterans who are using assistive technology (AT)"
title: "[ADE Research]: Team name - product name"
labels: ["508/Accessibility, ADE, ADE Research"]
assignees: sara-amanda,lakper,cindymerrill,artsymartha68
body:
- type: markdown
  attributes:
    value: "## About your team"
- type: input
  id: team-name
  attributes:
    label: What is the name of your team?
  validations:
    required: true

- type: input
  id: product
  attributes:
    label: What is the name of your product?
  validations:
    required: true

- type: input
  id: slack-channel
  attributes:
    label: What is the name of your product/team slack channel?
    description: We can use this channel to communicate about this ticket
  validations:
    required: false

- type: textarea
  id: team
  attributes:
    label: Who's on your team?
    description: This will help us reach out to you if needed
    value: |
      OCTO Product Owner:
      Product Manager:
      Designer/Researcher:
      Dedicated accessibility specialist on your team (if you have one):
      Accessibility Champ on your team (if you have one):
    
    render: bash
  validations:
    required: true

- type: markdown
  attributes:
    value: "## About your research study (if known)"

- type: input
  id: timeframe
  attributes:
    label: What is the timeframe for your testing?
    description: We will check on our team’s availability and then get back to you
  validations:
    required: true

- type: checkboxes
  id: research-details
  attributes:
    label: Are you allowing enough lead time?
    options:
      - label: Confirm you are filing this support ticket at least 2 weeks in advance of this timeframe, so there's enough lead time to provide support

- type: input
  id: num-participants
  attributes:
    label: How many participants using assistive tech do you want?
  validations: 
    required: false

- type: checkboxes
  id: AT-types
  attributes:
    label: What types of AT do you want to test?
    options:
      - label: Screen readers
      - label: Screen magnifiers
      - label: Speech recognition
      - label: Other
    
- type: checkboxes
  id: device-types
  attributes:
    label: What devices do you want to test?
    options:
      - label: Mobile phones
      - label: Tablets
      - label: Desktops/laptops
     
- type: textarea
  id: artifacts
  attributes:
    label: Supporting artifacts (if any)
    description: If relevant, please provide supporting artifacts as available
    value: |
      - [Product outline](Insert URL here between the parenthesis)
      - [User flows](Insert URL here between the parenthesis)
      - [Prototype or mockups](Insert URL here between the parenthesis)
      - [Research plan](Insert URL here between the parenthesis)
      - [Research conversation guide](Insert URL here between the parenthesis)
      - [Epics/issue that may be helpful](Insert URL here between the parenthesis)
      ...
  validations:
    required: true
- type: checkboxes
  id: next-steps
  attributes:
    label: Next steps
    description: Complete these after submitting this ticket with your ADE specialist
    options:
      - label: Post a link to this ticket in the accessibility-help Slack channel and tag Naomi `@Naomi Eke`
      - label: Your team's researchers and observers read through platform guidance on research with assistive technology users
      - label: Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/assistive-tech-pilot-guide.md) and request a pilot, if desired
      - label: ADE Specialists are assigned to your research, be sure to add the respective accessibility specialist(s) to your session invites (include the Zoom or Teams link). 
      - label: ADE Specialists review your conversation guide and research plan
      - label: Provide specialists your participant details like skill level, operating system, assistive tech used, browser
      - label: ADE specialists will provide you an optional feedback form to let us know how we can support y'all better into the future.
      - label: ADE Specialists create a research notes template
      - label: ADE Post research, specialists will add accessibility findings to your research folder
     
- type: dropdown
  id: champion-1
  attributes:
    label: Do you have an accessibility champion?
    description: If you don't have one, totally ok! Let us know if you're interested in becoming one. [Learn more about becoming an Accessibility Champion](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/accessibility/a11y-champs#accessibility-champions-community)

    options:
      - No, we don't have a champion (yet)
      - No, but we are interested in training one!
      - Yes, we have a champion
  validations:
    required: true


    
- type: input
  id: champion-3
  attributes:
    label: Is anyone on your team interested in becoming an accessibility champion?
    description: We'll reach out to them separately to get them started on their journey!
  validations:
    required: false


