name: "Assistive Technology Research Support Ticket (ADE)"
description: "Request support for research with disabled Veterans using screen readers, as their primary source of assistive technology and/or observation from an accessibility perspective."
title: "[ADE Accessibility Research]: Team name, product name"
labels: ["508/Accessibility, ADE, ADE Research"]
assignees: sara-amanda,lakper,cindymerrill,artsymartha68
body:
- type: markdown
  attributes:
    value: "## About your team"
- type: textarea
  id: team
  attributes:
    label: Who's on your team?
    description: This will help us reach out to you if needed
    value: |
      Team name:
      Product name:
      OCTO Product Owner:
      Product Manager:
      Designer/Researcher:
      Dedicated accessibility specialist on your team (if you have one):
      Accessibility Champ on your team (if you have one):
      Product/team slack channel (to communicate about this ticket):
      ...
    render: bash
  validations:
    required: true

- type: markdown
  attributes:
    value: "## About your research study (if known)"

- type: input
  id: timeframe
  attributes:
    label: What is the timeframe for your testing?
    description: We will check on our team’s availability and then get back to you
  validations:
    required: true

- type: input
  id: num-participants
  attributes:
    label: How many participants using assistive tech do you want?
  validations: 
    required: false

- type: checkboxes
  id: research-details
  attributes:
    label: Calendar checking
    description: Before moving forwards, please [review our capacity calendar for ADE availability](https://calendar.google.com/calendar/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a%40group.calendar.google.com&ctz=America%2FNew_York)
    options:
      - label: Confirm you are filing this support ticket at least 2 weeks in advance of this timeframe, so there's enough lead time to provide support

- type: checkboxes
  id: pilot
  attributes:
    label: Are you interested in doing a pilot of your study with a ADE accessibility specialist before the study begins?
    description: Review the [Assistive Technology Pilot Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/assistive-tech-pilot-guide.md) to learn about piloting with ADE.
    options:
      - label: Yes, we are interested in doing a pilot
    

    
- type: textarea
  id: artifacts
  attributes:
    label: Supporting artifacts (if any)
    description: If relevant, please provide supporting artifacts as available
    value: |
      - [Product outline](Insert URL here between the parenthesis)
      - [User flows](Insert URL here between the parenthesis)
      - [Prototype or mockups](Insert URL here between the parenthesis)
      - [Research plan](Insert URL here between the parenthesis)
      - [Research conversation guide](Insert URL here between the parenthesis)
      - [Epics/issue that may be helpful](Insert URL here between the parenthesis)
      ...
  validations:
    required: true
- type: checkboxes
  id: next-steps
  attributes:
    label: Next steps
    description: Complete these after submitting this ticket with your ADE specialist
    options:
      - label: Post a link to this ticket in the accessibility-help Slack channel and tag Naomi `@Naomi Eke`
      - label: Your team's researchers and observers read through platform guidance on research with assistive technology users
      - label: Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/assistive-tech-pilot-guide.md) and request a pilot, if desired
      - label: ADE Specialists are assigned to your research, be sure to add the respective accessibility specialist(s) to your session invites (include the Zoom or Teams link). 
      - label: ADE Specialists review your conversation guide and research plan
      - label: Provide specialists your participant details like skill level, operating system, assistive tech used, browser
      - label: ADE specialists will provide you an optional feedback form to let us know how we can support y'all better into the future.
      - label: ADE Specialists create a research notes template
      - label: ADE Post research, specialists will add accessibility findings to your research folder
     
- type: dropdown
  id: champion-1
  attributes:
    label: Do you have an accessibility champion?
    description: If you don't have one, totally ok! Let us know if you're interested in becoming one. [Learn more about becoming an Accessibility Champion](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/accessibility/a11y-champs#accessibility-champions-community)

    options:
      - No, we don't have a champion (yet)
      - No, but we are interested in training one!
      - Yes, we have a champion
  validations:
    required: true


    
- type: input
  id: champion-3
  attributes:
    label: Is anyone on your team interested in becoming an accessibility champion?
    description: We'll reach out to them separately to get them started on their journey!
  validations:
    required: false


