name: "Research Support Ticket (ADE)"
description: "Request support for user research with Veterans who are using assistive technology (AT)"
title: "[ADE Research]: Team name - product name"
labels: ["ADE, ADE Research"]
assignees: sara-amanda,lakper,cindymerrill,artsymartha68
body:

#> [!NOTE] 
#> - **High-Level Overview**: `Team Name`
#> - ** Services being utilized: (pilot, tech support, research planning)
#> - **Assistive Tech Users** for tech support: `TBD #` AT Users for studies (# recruited or “estimated” next to a number)
#> - **Artifacts Available**: `TBD` if waiting to receive from team
#> - **Testing Environment:** `TBD` if waiting to receive from team
#> - **Assistive Tech Being Used**: (screen readers, screen magnifiers, text to speech)

- type: markdown
  attributes:
    value: "## About your team"
- type: input
  id: team-name
  attributes:
    label: What is the name of your team?
  validations:
    required: true

- type: input
  id: product
  attributes:
    label: What is the name of your product?
  validations:
    required: true

- type: input
  id: slack-channel
  attributes:
    label: What is the name of your product/team slack channel?
    description: We can use this channel to communicate about this ticket
  validations:
    required: false

- type: textarea
  id: team
  attributes:
    label: Who's on your team? (names + slack handles if different from names)
    description: This will help us reach out to you if needed
    value: |
      OCTO Product Owner: 
      Product Manager:
      Designer/Researcher:
      Dedicated accessibility specialist on your team (if you have one):
      Accessibility Champ on your team (if you have one):
    
    render: bash
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ## What kind(s) of research help would you like from ADE?

- type: checkboxes
  id: help-research-materials
  attributes:
    label: Review research materials
    options:
      - label: Research plan
      - label: Recruitment criteria
      - label: Screening questions for inclusive recruiting
      - label: Conversation guide    
- type: checkboxes
  id: help-tech-support
  attributes:
    label: Provide technical support
    options:
      - label: Help building an accessible prototype
      - label: Pilot with an accessibility specialist
      - label: Live technical support during your AT research sessions  

- type: checkboxes
  id: help-moderation
  attributes:
    label: Help with research sessions
    options:
      - label: Advise on moderating AT research sessions
      - label: Have an accessibility researcher moderate your AT research sessions
      - label: Have an accessibility specialist observe your AT research sessions and document accessibility-related issues encountered  
      - label: Collaborate with an accessibility researcher to research a specific topic
      - label: Request accessibility research on a specific topic

- type: input
  id: research-topic
  attributes:
    label: If you want to request accessibility research, what is the topic?
    description: We will reach out to you to discuss this

- type: markdown
  attributes:
    value: |
      ## About your research study (fill in whatever you know at this time)

- type: input
  id: timeframe
  attributes:
    label: What is the timeframe for your testing?
    description: We will check on our team’s availability and then get back to you

- type: checkboxes
  id: research-details
  attributes:
    label: Are you allowing enough lead time?
    options:
      - label: Confirm you are filing this support ticket at least 2 weeks in advance of this timeframe, so there's enough lead time to provide support

- type: checkboxes
  id: AT-types
  attributes:
    label: What types of AT do you want to test?
    options:
      - label: Screen readers
      - label: Screen magnifiers
      - label: Speech recognition
      - label: Other
    
- type: input
  id: num-participants
  attributes:
    label: How many participants (total) using assistive tech (AT) are you planning?
  validations: 
    required: false

- type: checkboxes
  id: device-types
  attributes:
    label: What devices do you want to test?
    options:
      - label: Mobile phones
      - label: Tablets
      - label: Desktops/laptops
     
- type: checkboxes
  id: prototype-type
  attributes:
    label: What kind of prototypes (if any) are you planning?
    options:
      - label: GitHub Codespace 
      - label: CodePen
      - label: Staging
      - label: Other

- type: textarea
  id: artifacts
  attributes:
    label: Artifacts about your study (if you have any at this time)
    description: If relevant, please provide supporting artifacts as available
    value: |
      - [Product outline](insert URL here)
      - [User flows](insert URL here)
      - [Prototype or mockups](insert URL here)
      - [Research plan](insert URL here)
      - [Conversation guide](insert URL here)
      - [Research folder in github](insert URL here)
      - [Epics/issue that may be helpful](insert URL here)

- type: markdown
  attributes:
    value: |
      ## Next Steps


- type: checkboxes
  id: next-steps-team-now
  attributes:
    label: Next steps for you now
    description: After submitting this ticket, please complete the following tasks
    options:
      - label: Post a link to this ticket in the OCTO slack [accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) and tag Lakwi Perera and Cindy Merrill
      - label: Read Platform guidance on [research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users)
      - label: Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/digital-experience/ADE/assistive-tech-pilot-guide.md)

- type: checkboxes
  id: next-steps-team-later
  attributes:
    label: If ADE specialists are assigned to support your research sessions, you'll need to do these tasks after recruiting
    options:
      - label: Add each specialist to the corresponding session invite with videoconferencing link
      - label: Provide each specialist with your participant’s AT years of experience, device, operating system, assistive tech, and browser (if known)

- type: checkboxes
  id: next-steps-ADE
  attributes:
    label: This what ADE team members will do for you, depending on what you requested
    options:
      - label: Reply to you and schedule a meeting if needed
      - label: Assign accessibility specialist(s) to work with you
      - label: Review your research plan and conversation guide
      - label: Create a research notes template
      - label: Add accessibility findings to your research folder after the research sessions
      - label: Send optional feedback form  
    


