name: Authenticated Experience Change Request
description: Use this template to formally request a new feature, enhancement to a feature, discovery, research, analytics request or other ask/change for the Authenticated Experience team to evaluate.
title: "Change Request: [name of change]"
labels: [ "intake-process-ae", "authenticated-experience" ]
projects: ["department-of-veterans-affairs/1174"]
assignees: 
  - mtcA6
  - clantosswett
body:
- type: input
  id: requestor_name_and_email
  attributes:
    label: 1.) Requestor's Name and Email
    description: Add your full name and email here so we can contact you with any follow-up questions.
    placeholder: Example Name and Email
  validations:
    required: true
- type: input
  id: PO_name_and_email
  attributes:
    label: 2.) VA PO's Name and Email
    description: PO's name and email address so we can contact them with questions related to feature approval.
    placeholder: Example Name and Email
  validations:
    required: true
- type: input
  id: VA_Team_Slack_Channel
  attributes:
    label: 3.) VA Team and Slack Channel 
    description: The VA Team you are with (Health Products, Benefit Tools Crew, Identity, Contact Center, CAIA, etc.) and the best Slack channel to communicate with you.
    placeholder: 
  validations:
    required: true    
- type: textarea
  id: description_feature
  attributes:
    label: 4.) Please explain which product and features will be impacted.
    description: Please explain which product (MyVA/Dashboard, Authenticated Menu, Profile) / Features (Contact Information, Personal Information, Notification Settings, etc.). 
  validations:
    required: true
- type: textarea
  id: problem
  attributes:
    label: 5.) What is the problem you're trying to solve and the proposed solution?
    description: Describe the problem and its impact on the Veteran experience, and how the requested change is intended to work, so we can assess implementation. 
  validations:
    required: true
- type: textarea
  id: existing_documentation
  attributes:
    label: 6.) Please include all relevant documentation links for this change request.  
    description: Giving us access to documentation (product brief, APIs, research, Figma, Mural, flows, Github folder, etc.) will allow us to research and review existing materials.  
  validations:
    required: true
- type: input
  id: discussion_VAHB_PO
  attributes:
    label: 7.) Has this change been discussed with AuthExp PO (Chante)? 
    description: 
    placeholder:  Yes / No
  validations:
    required: true
- type: input
  id: va_stakedholer_alignment
  attributes:
    label: 8.) Has this change been agreed upon by all impacted VA Stakeholders? 
    description: 
    placeholder: Yes / No
  validations:
    required: true
- type: input
  id: duedate
  attributes:
    label: 9.) Is there a hard deadline associated with this request? 
    description: 
    placeholder: MM/DD/YYYY 
  validations:
    required: false
- type: textarea
  id: duedateexplanation
  attributes:
    label: 10.) Explain your deadline/target. Are there potential impacts to the product or other services if this deadline is not met?
    description: 
  validations:
    required: false
