name: Benefits Management Tools General Issue
description: Create a new issue (Task, Bug, Enhancement, Question, Design, or Accessibility)
title: "[Issue Type] [Short descriptive title]"
labels: ["benefits-management-tools", "issue"]
assignees: []

body:
  - type: dropdown
    id: feature
    attributes:
      label: Feature
      description: Select the feature this issue belongs to.
      options:
        - document-status
        - evidence-requests
        - decision-letter-notifications
        - other
    validations:
      required: true

  - type: input
    id: feature-other
    attributes:
      label: Specify Feature (if "Other")
      description: If you selected "other" above, specify the feature name. Leave blank otherwise.
      placeholder: Enter feature name…

  - type: dropdown
    id: team
    attributes:
      label: Team
      description: Select the team this issue belongs to.
      options:
        - "bmt-team-1 (Mavericks)"
        - "bmt-team-2 (Bee’s Knees)"
        - "bmt-team-3 (Phoenix)"
        - "Decision Reviews"
        - other
    validations:
      required: true

  - type: input
    id: team-other
    attributes:
      label: Specify Team (if "Other")
      description: If you selected "other" above, specify the team name. Leave blank otherwise.
      placeholder: Enter team name…

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: Select the type of issue you are creating.
      options:
        - Task
        - Bug
        - Enhancement
        - Question
        - Design
        - Accessibility
        - Other
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a short, descriptive summary of the issue.
      placeholder: "Short summary of the issue…"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description / Context
      description: |
        Provide details about the issue. Use the guidance below based on the Issue Type you selected.
      placeholder: |
        For **Bug**:
        1) Steps to reproduce…
        2) Expected behavior…
        3) Actual behavior…
        4) Environment (URL, browser, device)…

        For **Task / Enhancement / Other**:
        - Background/context…
        - What needs to be achieved (outcomes, not implementation)…
        - Risks/dependencies…

        For **Question**:
        - What decision or clarification is needed?
        - Options considered (if any)…
    validations:
      required: true

  # ---------- Design work ----------
  - type: textarea
    id: design-details
    attributes:
      label: Design Details (if applicable)
      description: Complete this section for Design issues (or if design updates are required).
      placeholder: |
        Problem to solve:
        Users affected / scenarios:
        Success criteria:
        Deliverables (wireframes, mockups, prototypes, content updates):
        Figma link(s):
        Reviewers / stakeholders:
        Accessibility considerations:
    validations:
      required: false

  # ---------- Accessibility work ----------
  - type: checkboxes
    id: a11y-scope
    attributes:
      label: Accessibility Scope (if applicable)
      description: Select the types of a11y work in scope.
      options:
        - label: Keyboard navigation & focus order
        - label: Screen reader support (NVDA/JAWS/VoiceOver/TalkBack)
        - label: Color and contrast
        - label: Semantics/landmarks/roles
        - label: Forms, labels, and error messaging
        - label: Motion/animation & prefers-reduced-motion
        - label: Reflow/zoom/responsive behavior
        - label: Other (describe below)
    validations:
      required: false

  - type: textarea
    id: a11y-details
    attributes:
      label: Accessibility Details (if applicable)
    validations:
      required: false

  # ---------- Acceptance Criteria ----------
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria / Definition of Done
      description: Define what “done” means for this issue. Use bullets or checkboxes.
      placeholder: |
        - [ ] Outcome 1 met
        - [ ] Outcome 2 met
        - [ ] Verified by reviewer(s)
    validations:
      required: false

  # ---------- Links & resources ----------
  - type: textarea
    id: resources
    attributes:
      label: Links & Resources
      description: Add any relevant links (design files, specs, logs, PRs, documentation).
      placeholder: |
        - Figma:
        - Related issues/PRs:
        - Monitoring/logs:
        - Docs:
    validations:
      required: false

  - type: input
    id: epic-link
    attributes:
      label: Related Epic
      description: |
        If this issue belongs to an Epic, paste the link or Epic number here.
        Example: https://github.com/department-of-veterans-affairs/va.gov-team/issues/123456
        Or simply: #123456
      placeholder: "Paste Epic link or reference (e.g., #123456)"
    validations:
      required: false

  # ---------- Sizing and Priority ----------
  - type: dropdown
    id: sizing
    attributes:
      label: Sizing Estimate (for capacity planning)
      description: Select a size estimate for this issue.
      options:
        - XS (very small, < 1 day)
        - S (small, 1–2 days)
        - M (medium, ~3–5 days)
        - L (large, ~1–2 weeks)
        - XL (very large, 2+ weeks / needs breaking down)
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 – Critical
        - P1 – High
        - P2 – Medium
        - P3 – Low
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ✅ **Reminder:**

        **Team Labels**
        Please apply the correct **Team label** after selecting your team above:
        - `bmt-team-1` → Mavericks
        - `bmt-team-2` → Bee’s Knees
        - `bmt-team-3` → Phoenix
        - Or another team label if applicable

        **Issue Type**
        Make sure you select the right **Issue Type** in the dropdown above:
        - **Task** → Work to be done, implementation steps
        - **Bug** → Defect, error, or unexpected behavior
        - **Enhancement** → Improvement or optimization to existing functionality
        - **Question** → Clarification or decision needed
        - **Design** → UX/UI design, mockups, prototypes, content changes
        - **Accessibility** → A11y-specific issues (WCAG, screen readers, color contrast, etc.)

        **Issue Labels**
        Apply any additional labels that may be relevant (e.g., issue type, priority).
        This helps keep issues organized and ensures visibility across the Benefits Management Tools portfolio.
