name: Benefits Content Practice Template
description: Issue template for requesting content design support for Decision Reviews/BMT 1/BMT 2
title: "[Content] Product: Feature - Request"
labels:
  - content
  - hcd
assignees:
  - cinlackey

body:
  - type: markdown
    attributes:
      value: |
        ## ✏️ Content Support Request
        This form is for requesting content design support for work related to Decision Reviews (DR) and Benefits Management Tools Teams 1 & 2 (BMT 1 & BMT 2).
        Please fill out the sections below to help us understand your request, prioritize it effectively, and coordinate with the right stakeholders.

  - type: dropdown
    id: support_type
    attributes:
      label: 🛠 What kind of content support is needed?
      description: Review the [content design menu](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1746655929211/80067a3f9875681b70f4a854ce74388504c5c1de?sender=uf5838c6c24bc1098b12b5304) and select the most relevant category.
      multiple: true
      options:
        - Identify content needs
        - Analyze existing content (in production)
        - Create new content
        - Review content already created by design team (not yet in production)
        - Content on prototypes for testing
        - Content validation during testing
        - Refine content based on testing
        - Other, like a workshop

  - type: input
    id: support_other
    attributes:
      label: If "Other" is selected above, please describe
      placeholder: Describe typw of work here...

  - type: textarea
    id: value_statement
    attributes:
      label: Value Statement
      placeholder: 'As a Veteran... I want to... so that...'
      
  - type: textarea
    id: request_summary
    attributes:
      label: Summary of request
      placeholder: What are you building and why does it matter?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - 🏃‍♂️ **High:** Must complete before the next sprint ends (e.g., blocks other work, part of the Collaboration Cycle, or has an external deadline)
        - 🌼 **Medium:** Important but not urgent (e.g., unblocks near-future work or is needed for an upcoming milestone)
        - 🐢 **Low:** Nice to have (e.g., not time-sensitive, no major dependencies, won't block others if delayed)

  - type: dropdown
    id: effort
    attributes:
      label: Effort
      options:
        - 🐜 **Small:** Simple revision (e.g., editing a sentence or two)
        - 🐈 **Medium:** Moderate update (e.g., editing a couple of sections or revising a page)
        - 🐘 **Large:** Full review and rework (e.g., multiple screens, new content, or net-new flow)

  - type: textarea
    id: links
    attributes:
      label: 🔗 Relevant Links
      placeholder: "Include Figma, GitHub tickets, Collaboration Cycle, Mural, or other references."

  - type: textarea
    id: dates_meetings
    attributes:
      label: 📅 Important Dates and Meetings
      placeholder: "Timeline expectations, collaboration cycle stage, or meeting invites."

  - type: checkboxes
    id: stakeholders
    attributes:
      label: 👥 Stakeholders
      options:
        - label: Enablement Product
        - label: Enablement Design
        - label: Design
        - label: Engineering
        - label: Accessibility
        - label: OBA
        - label: Other
  
  - type: input
    id: stakeholders_other
    attributes:
      label: If "Other" is selected above, please describe
      placeholder: Describe additional stakeholders here...
    
  - type: textarea
    id: open_questions
    attributes:
      label: Open Questions
      placeholder: List any outstanding decisions or questions.

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      placeholder: "e.g., Waiting for updated design, research input, or engineering review."

  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of Content Scope
      placeholder: List items that are not part of this request.

  - type: textarea
    id: tasks_list
    attributes:
      label: "📋 Task List"
      description: "List the tasks for this request. Use `- [ ]` to create checkboxes so they can be checked off later. It's okay to leave this minimal or blank for the Content Designer to fill out later."
      placeholder: |
        Example:
        - [ ] Review current content
        - [ ] Draft new headings
        - [ ] Share with stakeholders
    validations:
      required: false

  - type: checkboxes
    id: definition_ready
    attributes:
      label: Definition of Ready (to be completed by the content designer)
      options:
        - label: Clear value statement
        - label: Figma or reference materials available
        - label: Timeline, blockers, and reviewers identified
        - label: Scope and expectations are aligned

  - type: checkboxes
    id: definition_done
    attributes:
      label: Definition of Done (to be completed by the content designer)
      options:
        - label: Final content reviewed by stakeholder(s)
        - label: Ready for handoff
        - label: Guidance is clear and accessible
        - label: No outstanding questions or blockers
