name: Benefits Management Tools General Issue
description: Create a new issue (Task, Bug, Enhancement, Question, Design, Accessibility, or Spike)
title: "[Issue Type] [Short descriptive title]"
labels: ["benefits-management-tools", "issue", "product-backlog"]
assignees: []

body:
  - type: dropdown
    id: feature
    attributes:
      label: Feature
      description: Select the feature this issue belongs to.
      options:
        - document-status
        - evidence-requests
        - decision-letter-notifications
        - Intent-to-file (ITF)
        - other
    validations:
      required: true

  - type: input
    id: feature-other
    attributes:
      label: Specify Feature (if "Other")
      description: If you selected "other" above, specify the feature name. Leave blank otherwise.
      placeholder: Enter feature name…

  - type: dropdown
    id: team
    attributes:
      label: Team
      description: Select the team this issue belongs to.
      options:
        - "bmt-team-1 (Mavericks)"
        - "bmt-team-2 (Bee’s Knees)"
        - "bmt-team-3 (Phoenix)"
        - "Decision Reviews"
        - other
    validations:
      required: true

  - type: input
    id: team-other
    attributes:
      label: Specify Team (if "Other")
      description: If you selected "other" above, specify the team name. Leave blank otherwise.
      placeholder: Enter team name…

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: Select the type of issue you are creating.
      options:
        - Task
        - Bug
        - Enhancement
        - Question
        - Design
        - Accessibility
        - Spike
        - Other
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a short, descriptive summary of the issue.
      placeholder: "Short summary of the issue…"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description / Context
      description: |
        Provide details about the issue. Use the guidance below based on the Issue Type you selected.
      placeholder: |
        For **Bug**:
        1) Steps to reproduce…
        2) Expected behavior…
        3) Actual behavior…
        4) Environment (URL, browser, device)…

        For **Task / Enhancement / Other**:
        - Background/context…
        - What needs to be achieved (outcomes, not implementation)…

        For **Question**:
        - What decision or clarification is needed?
        - Options considered (if any)…
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks / Dependencies
      description: Capture any known risks, blockers, or dependencies related to this issue.
      placeholder: |
        - Risk: Potential GA event volume cost
        - Dependency: Requires input from vfs-analytics
        - Dependency: Backend cleanup (EVSS removal)
    validations:
      required: false

  # ---------- Design work ----------
  - type: textarea
    id: design-details
    attributes:
      label: Design Details (if applicable)
      description: Complete this section for Design issues (or if design updates are required).
      placeholder: |
        Problem to solve:
        Users affected / scenarios:
        Success criteria:
        Deliverables (wireframes, mockups, prototypes, content updates):
        Figma link(s):
        Reviewers / stakeholders:
        Accessibility considerations:
    validations:
      required: false

  # ---------- Accessibility work ----------
  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility Scope & Details (if applicable)
      description: Capture any accessibility considerations or requirements for this issue.
      placeholder: |
        If accessibility work is required, describe the scope and details here.  
        Examples:  
        - Keyboard navigation & focus order  
        - Screen reader support (NVDA/JAWS/VoiceOver/TalkBack)  
        - Color and contrast  
        - Semantics/landmarks/roles  
        - Forms, labels, and error messaging  
        - Motion/animation & prefers-reduced-motion  
        - Reflow/zoom/responsive behavior  
        - Other accessibility considerations  
    validations:
      required: false

  # ---------- Acceptance Criteria ----------
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria / Definition of Done
      description: Define what “done” means for this issue. Use bullets or checkboxes.
      placeholder: |
        - [ ] Outcome 1 met
        - [ ] Outcome 2 met
        - [ ] Verified by reviewer(s)
    validations:
      required: false

  # ---------- Links & resources ----------
  - type: textarea
    id: resources
    attributes:
      label: Links & Resources
      description: Add any relevant links (design files, specs, logs, PRs, documentation).
      placeholder: |
        - Figma:
        - Related issues/PRs:
        - Monitoring/logs:
        - Docs:
    validations:
      required: false

  - type: input
    id: epic-link
    attributes:
      label: Related Epic
      description: |
        If this issue belongs to an Epic, paste the link or Epic number here.
        Example: https://github.com/department-of-veterans-affairs/va.gov-team/issues/123456
        Or simply: #123456
      placeholder: "Paste Epic link or reference (e.g., #123456)"
    validations:
      required: false

  # ---------- Estimation and Priority ----------
  - type: dropdown
    id: estimate
    attributes:
      label: Estimate
      description: |
        Select an initial effort estimate for this issue.  
        ⚠️ This can be filled upon issue creation and refined during sprint planning.
      options:
        - 1 – Very minuscule, less than a day
        - 2 – Small, ~1 day
        - 3 – Medium sized, a couple of days
        - 5 – Bigger effort, about a week
        - 8 – Likely about a full sprint
        - 13 – Big effort, multiple sprints (consider breaking down)
    validations:
      required: false

  - type: input
    id: points
    attributes:
      label: Points
      description: |
        Enter a numeric value for story points if needed.  
        ⚠️ This can be filled upon issue creation and refined during sprint planning.
      placeholder: "e.g., 3"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: |
        Select the priority level for this issue.  
        ⚠️ This can be set when creating the issue and refined later during backlog grooming or sprint planning.
      options:
        - Lowest
        - Medium
        - Highest
        - Pinned
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ✅ **Reminder:**

        **Team Labels**
        Apply the correct **Team label** after selecting your team above:
        - `bmt-team-1` → Mavericks
        - `bmt-team-2` → Bee’s Knees
        - `bmt-team-3` → Phoenix
        - Or another team label if applicable

        **Issue Type Labels**
        Make sure you select the right **Issue Type** in the dropdown above:
        - **Task** → Work to be done, implementation steps
        - **Bug** → Defect, error, or unexpected behavior
        - **Enhancement** → Improvement or optimization to existing functionality
        - **Question** → Clarification or decision needed
        - **Design** → UX/UI design, mockups, prototypes, content changes
        - **Accessibility** → A11y-specific issues (WCAG, screen readers, color contrast, etc.)

        **Feature Labels**
        Use labels to identify which product area the issue belongs to:
        - `doc-status`
        - `evidence-requests`
        - `intent-to-file`
        - Or other feature-specific labels as appropriate

        **Workstream Labels**
        Apply labels to indicate the discipline or focus area:
        - `ux`
        - `eng-frontend`
        - `eng-backend`
        - `accessibility`
        - `content`
        - Or other workstream labels as appropriate
