name: BIO Aquia - Issue Template
description: Issues for BIO Aquia
labels: ["benefits-optimization", "benefits-optimization-aquia", "needs-grooming"]
projects: 
- department-of-veterans-affairs/1808
type: Task

body:
- type: textarea
  attributes:
    label: Add a description
  validations:
    required: false
