name: "Assistive Technology Research Support Ticket (CAIA)"
description: "Request support for research with disabled Veterans using assistive technology"
title: "[CAIA A11y Research]: Team name, product name"
labels: ["508/Accessibility, sitewide CAIA, sitewide accessibility"]
assignees: [coforma-terry, angelafowler82]
body:
- type: markdown
  attributes:
    value: "## Your team's information"
- type: textarea
  id: team
  attributes:
    label: Who's on your team?
    description: This will help us reach out to you if needed
    value: |
      Team name:
      OCTO-DE product owner:
      Product manager:
      Designer:
      FE engineer:
      Product/team Slack channel:
      ...
    render: bash
  validations:
    required: true

- type: dropdown
  id: champion-1
  attributes:
    label: Do you have an accessibility champion on your team?
    description: If you don't have one, totally ok! Let us know if you're interested in becoming one.
    options:
      - Yes
      - No
      - I'm interested in becoming one!
  validations:
    required: true

- type: input
  id: champion-2
  attributes:
    label: If you have an accessibility champion, what's their name?
    description: We'll aim to partner with them if they have time.
  validations:
    required: false
    
- type: input
  id: champion-3
  attributes:
    label: Is anyone on your team interested in becoming an accessibility champion?
    description: We'll reach out to them separately to get them started on their journey!
  validations:
    required: false

- type: markdown
  attributes:
    value: "## Research details"
- type: markdown
  attributes:
    value: |
     Before moving forwards, please:
       1. [Review our capacity calendar for CAIA availability](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago)
       2. Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
       3. Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support
     If CAIA support is available during your timeframe, we are good to go! Otherwise, we recommend pushing back your research if possible until there is available support.

- type: checkboxes
  id: calendar
  attributes:
    label: Have you reviewed the CAIA research calendar?
    description: Make sure your research's timeframe occurs when we have time to support y'all
    options:
      - label: Yes
  validations:
    required: true
    
- type: input
  id: timeframe
  attributes:
    label: When is the timeframe for your testing?
  validations:
    required: true
    
- type: textarea
  id: artifacts
  attributes:
    label: Supporting artifacts (if any)
    description: If relevant, please provide supporting artifacts as available
    value: |
      - [Product outline](Insert URL here between the parenthesis)
      - [User flows](Insert URL here between the parenthesis)
      - [Prototype or mockups](Insert URL here between the parenthesis)
      - [Research plan](Insert URL here between the parenthesis)
      - [Research conversation guide](Insert URL here between the parenthesis)
      - [Epics/issue that may be helpful](Insert URL here between the parenthesis)
      ...
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Next steps"
- type: markdown
  attributes:
    value: |
      - [ ] [Your team]: Post a link to this ticket in the #accessibility-help Slack channel and tag Terry Nichols.
      - [ ] [Your team]: [Your team's researchers and observers read through platform guidance on research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-assistive-technology-sessions)
      - [ ] [CAIA]: Specialists are assigned to your research 
      - [ ] [CAIA]: Specialists review your conversation guide and research plan
      - [ ] [Your team]: Provide specialists your participant details (skill level, operating system, assistive tech used, browser)
      - [ ] [CAIA]: [Specialists create a research notes template](https://docs.google.com/spreadsheets/d/1YzcNjUgnFS2JSnQD7IuaNx8MMH07M3xshqmepOCEKfs/edit?usp=sharing)
      - [ ] [CAIA]: Post research, https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/accessibility-findings-template.md
      
      
