name: "Collaboration Cycle Request"
description: "Begin engaging with the Collaboration Cycle."
title: "Collaboration Cycle for [Team Name, Product Name, Feature Name]"
labels: ["collab-cycle-review", "collaboration-cycle", "CC-Request", "sitewide CAIA"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "# Collaboration Cycle"
  - type: markdown
    attributes:
      value: |
        The [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) is where teams who are building products on VA.gov get feedback and guidance on their product/feature to ensure it meets VA.gov experience standards. Teams engage with the Collaboration Cycle throughout their product’s/feature's lifecycle.
  - type: markdown
    attributes:
      value: |
        Before engaging with the Collaboration Cycle, please review the questions below to help Platform determine what level of support and which touchpoints are needed for your work. (Learn more about the [Collaboration Cycle kickoff](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff).)
  - type: markdown
    attributes:
      value: |
        **Fields marked with an asterisk (*) are required.**
  - type: markdown
    attributes:
      value: "## VFS product or feature information"
  - type: checkboxes
    id: verify-directory
    attributes:
      label: Verify information about your product or feature in the VFS Product Directory.
      options:
        - label: I have reviewed the [VFS Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory) and confirm that my information is correct (or that I have taken appropriate actions to update or add my product information to the directory).
          required: true
  - type: input
    id: product-team
    attributes:
      label: VFS team name
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: product-name
    attributes:
      label: Product name
      description: See [terms and definitions on products vs. features](https://depo-platform-documentation.scrollhelp.site/getting-started/product-operations-terms-and-definition).
    validations:
      required: true
  - type: input
    id: feature-name
    attributes:
      label: Feature name
      description: See [terms and definitions on products vs. features](https://depo-platform-documentation.scrollhelp.site/getting-started/product-operations-terms-and-definition).
    validations:
      required: true
  - type: input
    id: team-label
    attributes:
      label: GitHub label for team
      description: Enter a label from the va.gov-team repo. Your team label must be different than your product label.
    validations:
      required: true
  - type: input
    id: product-label
    attributes:
      label: GitHub label for product
      description: Enter a label from the va.gov-team repo. Your product label must be different than your team label.
    validations:
      required: true
  - type: input
    id: feature-label
    attributes:
      label: GitHub label for feature
      description: Enter a label from the va.gov-team repo, if applicable.
    validations:
      required: false
  - type: input
    id: slack-channel
    attributes:
      label: Public DSVA Slack channel for VFS team
    validations:
      required: true
  - type: input
    id: start-date
    attributes:
      label: When did/will you start working on this product/feature?
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Kickoff questions"
  - type: markdown
    attributes:
      value: |
        Please refer to the guidance on the [Collaboration Cycle Kickoff](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff) page on Platform Website for detailed information and examples regarding these questions (below).
  - type: dropdown
    id: visible-changes
    attributes:
      label: Will your work result in visible changes to the user experience?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: user-research
    attributes:
      label: Are you doing research with VA.gov users?
      options:
        - "Yes"
        - "No"
        - "Unsure"
    validations:
      required: true
  - type: dropdown
    id: changes-to
    attributes:
      label: Will your work involve changes to...
      description: For tools and applications, take into account if any static page entry points will need updates. For information and examples of Static vs Dynamic pages, review the [Static vs Dynamic guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md).
      options:
        - "Tools, applications and dynamic pages"
        - "Static pages"
        - "Both"
        - "Other"
    validations:
      required: true
  - type: dropdown
    id: architecture-intent
    attributes:
      label: Does your work require non-trivial code changes or involve PII/PHI?
      description: If so, you need an [engineering and security review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md).
      options:
        - "Yes"
        - "No"
        - "Unsure"
  - type: dropdown
    id: analytics-domo
    attributes:
      label: Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?
      options:
        - "Yes"
        - "No"
        - "Unsure"
    validations:
      required: true
  - type: dropdown
    id: other-analytics
    attributes:
      label: Do you need to capture any additional analytics or metrics?
      options:
        - "Yes"
        - "No"
        - "Unsure"
    validations:
      required: true
  - type: dropdown
    id: cms
    attributes:
      label: Will a VA editor (Drupal) notice this change?
      description: A VA editor creates content that informs the public about VA facilities - operating hours, services offered at specific locations - or else public content that describes benefits and procedures for applying for them.
      options:
        - "Yes"
        - "No"
        - "Unsure"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Artifacts"
  - type: input
    id: product-outline
    attributes:
      label: Product outline
      description: Please enter a URL for your product outline. See the [product outline template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md).
    validations:
      required: true
  - type: checkboxes
    id: artifact-links-checkbox
    attributes:
      label: Verify all relevant materials provided to Governance Team
      options:
        - label: I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product
          required: true
  - type: markdown
    attributes:
      value: "## Next steps"
  - type: checkboxes
    id: add-labels
    attributes:
      label: Add the GitHub labels for your team, product, and feature to this ticket.
      description: This helps Platform and OCTO track your progress through the Collab Cycle and helps improve overall reporting for all products on VA.gov.
      options:
        - label: I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket. 
          required: true

