name: Accessibility Design Review – Intake Form
description: Intake form to prepare for an accessibility design review
title: "[A11y Design Review] "
labels:
  - disability-experience
  - needs-a11y-refinement
assignees:
  - etanb
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Summary
        Please fill out all fields clearly to ensure we can provide helpful and timely feedback.

  - type: input
    id: feature_name
    attributes:
      label: Feature name
      placeholder: e.g., Disability Benefits Form Update
    validations:
      required: true

  - type: textarea
    id: feature_summary
    attributes:
      label: Brief summary of the feature and what it aims to solve or improve
      placeholder: Describe the purpose, users affected, and expected outcomes.
    validations:
      required: true

  - type: input
    id: team_name
    attributes:
      label: Team name
      placeholder: e.g., Disability Benefits 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 👥 Point of Contact"

  - type: input
    id: product_owner
    attributes:
      label: Product owner name
    validations:
      required: true

  - type: input
    id: designer_contact
    attributes:
      label: Designer contact name
    validations:
      required: true

  - type: input
    id: engineers
    attributes:
      label: Engineer(s) name(s) (optional)
      placeholder: Optional

  - type: input
    id: slack_channel
    attributes:
      label: Slack channel for follow-up
      placeholder: e.g., #accessibility-help
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 📁 Resources"

  # Combined Figma/Mural/etc. links into a single textarea
  - type: textarea
    id: design_links
    attributes:
      label: Design links (Figma, Mural, etc.)
      description: "Provide URLs and specify frame/page names to review."
      placeholder: |
        Figma: https://www.figma.com/file/...
        Mural: https://app.mural.co/t/... (Board: ___, Section: ___)
    validations:
      required: false

  # Combined screenshots + videos into one attachments field
  - type: attachments
    id: visuals
    attributes:
      label: Visuals & walkthroughs
      description: "Upload screenshots or short videos, or paste links to hosted files."
    validations:
      required: false

  - type: textarea
    id: other_docs
    attributes:
      label: Other relevant documents or links
      placeholder: e.g., PRD, user research notes, prior a11y findings
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## ✅ Next Steps"

  - type: markdown
    attributes:
      value: |
        1. Etan will move the ticket Status from "New" to "Assigned".
        2. Etan will reach out directly with the Design POC to coordinate.
