name: "Content & IA Product Support Request"
description: "Partner with the CAIA shared services team on a new initiative"
title: "[INTAKE] ${{ inputs.team_name }}: ${{ inputs.initiative_name }}"
labels:
  - caia-intake
body:
  - type: input
    id: team_name
    attributes:
      label: "Team name"
      placeholder: "Benefits Platform"
    validations:
      required: true

  - type: input
    id: initiative_name
    attributes:
      label: "Initiative name"
      placeholder: "VA Disability Claims Tool revamp"
    validations:
      required: true

  - type: textarea
    id: intake_form
    attributes:
      label: "Intake form"
      description: "Please fill out all fields in the Markdown template below"
      value: |
        ## Team info
        | Field | Value |
        | ----- | ----- |
        | **Product name** | <!-- e.g. VA Disability Claims Tool --> |
        | **Team name** | ${{ inputs.team_name }} |
        | **Slack channel** | <!-- e.g. #benefits-platform --> |
        | **OCTO product owner** | |
        | **Product manager** | |
        | **Designer(s)** | |
        | **Dedicated content writer (if any)** | |

        ---

        ## About your initiative

        ### Target audiences (select all that apply)
        - [ ] Veterans / family / caregivers
        - [ ] Other VA.gov audience — describe below
        - [ ] Internal designers / product teams (patterns and standards)

        ### Engagement type (select all that apply)
        - [ ] Digitizing a new form  
        - [ ] Creating a new digital tool  
        - [ ] Updating an existing form or tool  
        - [ ] Translating into Spanish  
        - [ ] Adding new unauthenticated content  
        - [ ] Updating existing unauthenticated content  
        - [ ] Components, patterns, or standards  
        - [ ] Other — explain below

        ### Work summary
        <!-- Briefly describe what will be built or updated -->

        ### Supporting artifacts
        <!-- Add any links that exist today -->
        - Product outline:
        - Collaboration-Cycle ticket:
        - Content source-of-truth doc:
        - Figma:
        - Mural:

        ### Timeline
        | Item | Detail |
        | ---- | ------ |
        | **Estimated launch** | <!-- YYYY-MM-DD --> |
        | **Current phase** | <!-- wireframes / in dev / UAT --> |
        | **Staged launch?** | <!-- Yes/No. If yes, outline phases --> |
    validations:
      required: true 
