name: Disability Benefits - Content Support Request Template
description: Content support request for the Disability Benefits Crew
title: "[INTAKE] Team name: Initiative name"
labels: ["disability", "disability-benefits", "content"]
projects:
- department-of-veterans-affairs/1660
type: Task
assignees: amylago

body:
- type: markdown
  attributes:
    value: |
      Use this ticket to ask the Disability Benefits Crew (DBC) content designer for support. Use clear, simple language and action verbs to describe the work. Avoid acronyms and jargon.

      ## 👥 Team info
      Tell us about your team.
- type: input
  attributes:
    label: Product name
    placeholder: e.g., VA 21-0781
  validations:
    required: true
- type: input
  attributes:
    label: Team name
    placeholder: e.g., Disability Benefits Crew Core Form team
  validations:
    required: true
- type: input
  attributes:
    label: Slack channel
  validations:
    required: true
- type: input
  attributes:
    label: Product manager
  validations:
    required: true
- type: input
  attributes:
    label: Designer(s)
  validations:
    required: true
- type: input
  attributes:
    label: VA design lead
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Which of these descriptions best fits the work we will partner on? (select all that apply)
    options:
      - label: Digitizing a new form
      - label: Updating an existing form
      - label: Incorporating C&IA content feedback

  - type: textarea
  attributes:
    label: User need 
    description: As a **user**, I want to **do something** so that **something happens**.
  
  - type: textarea
  attributes:
    label: Description
    description: Describe the scope of this work, background context, why it matters, dependencies, goals, and open questions.

- type: markdown
  attributes:
    value: |
      ## 📑 Supporting Artifacts
      Add links to all applicable artifacts and issues.

- type: input
  attributes:
    label: Parent epic or super epic
  validations:
    required: true
- type: input
  attributes:
    label: Figma file
  validations:
    required: true
- type: input
  attributes:
    label: Mural 
- type: input
  attributes:
    label: "Collaboration Cycle ticket #"
- type: input
  attributes:
    label: Research findings or usability insights


- type: textarea
  attributes:
    label: Technical constraints
    description: Describe any technical considerations or constraints.

- type: input
  attributes:
    label: Timeline
    description: Provide information about your expected/planned timeline.
    placeholder: Estimated launch timeline
- type: input
  attributes:
    label: Where are you in your design/development process?
- type: input
  attributes:
    label: Is a staged launch planned?
    description: If so, please provide details.
