name: Identity Frontend
description: For writing frontend tickets
labels: "Identity,Identity-Frontend"
projects:
  - department-of-veterans-affairs/1137
body:
- type: textarea
  attributes:
    label: Issue Description
    description: Describe the issue details
    placeholder: Insert issue details here
- type: markdown
  attributes:
    value: |
      ## Front end tasks

      - Ensure the page is styled according to design spec. 

      - Ensure the back end data from API is displayed in local and review instance

      - Ensure unit tests are available. 

      - Ensure your code changes are covered by E2E tests

      - Run axe checks using the Chrome or Firefox browser plugin

      - Test for color contrast and color blindness issues

      - Zoom layouts to 400% at 1280px width

      - Test with 1 or 2 screen readers

      - Navigate using the keyboard only


      ## Acceptance Criteria

      - [ ] Designer comments on this issue to approve page styling 

      - [ ] Unit tests pass

      - [ ] E2E tests cover current code and regression

      - [ ] End-to-end tests show 0 violations.

      - [ ] The data returned matches API response (for given user or scenario)

      - [ ] All axe checks pass

      - [ ] All color contrast checks pass

      - [ ] All zoom testing passes

      - [ ] All keyboard checks pass 

      - [ ] All screenreader checks pass


      ## Appendix

      <details> 

        <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
        
        - Add E2E tests if none exist for this addition/change. 
        
        - Update existing E2E tests if this code will change functionality. 
        
        - Include axe checks, including hidden content
        
      </details>


      <details> 

        <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
        
      - Ensure no heading levels are skipped.


      - Ensure all buttons and labeled inputs use semantic HTML elements.


      - Ensure all buttons, labeled elements and images are identified using HTML
      semantic markers or ARIA roles.


      - Ensure form fields have clearly defined boundaries or outlines.


      - Ensure form fields do not use placeholder text. 


      - Ensure form fields have highly visible and specific error states. 


      </details>


      <details> 

        <summary> Test for color contrast and color blindness issues (expand) </summary>
        - All text has appropriate contrast. 

      </details>


      <details> 

        <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
        - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
        - Ensure no content gets focused offscreen or is hidden from view.
        
      </details>


      <details> 

        <summary> Test with 1 or 2 screen readers (expand)</summary> 
        
        - Ensure the page includes a skip navigation link. 
        
        - Ensure all links are properly descriptive. 
        
        - Ensure screen reader users can hear the text equivalent for each image conveying information. 

        - Ensure screen reader users can hear the text equivalent for each image button. 

        - Ensure screen reader users can hear labels and instructions for inputs. 
        
        - Ensure purely decorative images are not announced by the screenreader. 
        
      </details>


      <details> 

        <summary>Navigate using the keyboard only (expand)</summary> 
        
        - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
        
        - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
        
        - Ensure all interactive elements can be reached with the tab key in a logical order 
        
        - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
        
        - Ensure focus is always visible and appears in logical order.
        
        - Ensure each interactive element has visible focus state which appears in logical order.
        

      </details>


      #### Product notes



      #### Tech notes


      ---

      ## How to configure this issue

      - [ ] **Attached to a Milestone** (when will this be completed?)

      - [ ] **Attached to an Epic** (what body of work is this a part of?)

      - [ ] **Labeled with Team** (`product support`, `analytics-insights`,
      `operations`, `service-design`, `Console-Services`, `tools-fe`)

      - [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`,
      `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`,
      `research`, `accessibility`, `content`)

      - [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`,
      etc.)
