name: "MHV Accessibility Issue Ticket"
description: "Please use this form to report or create an accessibility issue ticket for MHV"
title: "[a11y-defect-x]: MHV:[Product]: [Issue description]"
labels: ["accessibility", "a11y-testing", "needs-refinement"]
projects: ["department-of-veterans-affairs/1748"]
assignees: ["steveg-IAT", "sarahhortonadhoc"]
body:
- type: markdown
  attributes:
    value: "# MHV Accessibility Issue Ticket"

- type: markdown
  attributes:
    value: |      
      > [!TIP]
      > Title format: [a11y-defect-SEVERITY]: MHV:[Product > MedRecs | Meds | SecMess | SS]: [Brief Issue description]

- type: markdown
  attributes:
    value: |
      ## Issue Description
    
- type: textarea
  id: details
  attributes:
    label: ðŸ“ User story
    description: "Define the user story. Don't forget the 'SO THAT' statement."
    placeholder: |
      As a [user role], 
      I want to [action]       
      so that [I can achieve my goal]
      ...
    
- type: textarea
  id: problem
  attributes:
    label: ðŸ“ Problem statement
    description: "Illustrate how the defect affects users. If you have a screenshot or video, add those here and/or to the attachments field after the ticket is created."
    placeholder: |
      [Instead of the desired action, this happens...]
      ...

- type: textarea
  id: evidence
  attributes:
    label: ðŸŒŒ Supporting screenshots or videos
    description: "Attach any supporting material. An annotated picture is worth a 1,000 meetings."
    placeholder: |
      [Add screenshot or video here]
      ...

- type: textarea
  id: repro
  attributes:
    label:  ðŸ‘£ Reproduction steps
    description: "How do you trigger this issue? Please walk us through it step by step. Include test user and any relevant device, browser, and assistive technology."
    placeholder: |
      1. Using [browser] with [assistive technology] as [test user],
      2. Navigate to... this page
      3. Navigate to...
      4. Use component...
      5. Notice issue...  
      ...
  validations:
    required: true

- type: input
  id: contact
  attributes:
    label: ðŸ”— Point of contact
    description: The person who wrote or is responsible for this ticket. Usually an a11y specialist.
    placeholder: "Name (GitHub ID) - Sarah Horton (@sarahhortonadhoc) | Steven Gallagher (@steveg-IAT)"
  validations:
    required: true

- type: dropdown
  id: severity
  attributes:
    label: âš ï¸ Severity level
    description: "Don't forget to add a corresponding label to this ticket once it's created (a11y-defect-0, a11y-defect-1, etc.)"
    options:
      - 0, Launchblocker. Potentially Harmful. Must be fixed immediately.
      - 1, Launchblocker. Critical. Must be fixed before launch.
      - 2, Serious. Should be fixed in 1-2 sprints post-launch.
      - 3, Moderate. Should be fixed in 1-3 sprints post-launch.
      - 4, Minor. Consider fixing or exploring in 2-4 sprints post-launch.

- type: textarea
  id: references
  attributes:
    label: ðŸ”Ž Relevant standards
    description: "Provide any relevant documentation, VADS component, or other evidence as to why this is an issue or how to fix it. Don't forget to add a corresponding label(s) to this ticket once it's created. (wcag-1.1.1, 508-issue-cognition, etc)."
    placeholder: |
      #### Accessibility Standards
      1. [Understanding WCAG 2.2 (W3C)](https://www.w3.org/WAI/WCAG22/Understanding/)
      2.
      #### Experience Standards
      1. [VA Design System Experience Standards](https://design.va.gov/about/experience-standards/)
      2.
      ...

- type: markdown
  attributes:
    value: |
      ---

- type: markdown
  attributes:
    value: |
      ## Recommended Actions

- type: textarea
  id: solution
  attributes:
    label: ðŒ£ Proposed solution or next steps
    description: "If there is an easy HTML, CSS, or JavaScript markup fix, add it after creating this ticket. If it is a longer fix or you do not have a ready solution, provide next steps."
    placeholder: |
      [Do this action to bring the issue into compliance.]
      ...
      
- type: textarea
  id: acceptance
  attributes:
    label:  âœ… Acceptance criteria
    description: "What will success look like?"
    placeholder: |
      - The system displays...
      - The system provides...
      - The user can...

- type: checkboxes
  id: tasks
  attributes:
    label: âœ… Possible tasks
    options:
      - label: Review, refine, and acknowledge feedback.
      - label: Update ticket information (title, assignee, labels, project(s), etc.)
      - label: Fix and/or document decisions made.
      - label: Product manager to move ticket in their respective product board to 'QA/A11y Review' after reviewing documented decisions / validating fix.
      - label: Accessibility specialist will close the ticket after reviewing documented decisions / validating the fix.    
    
- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > **QUICK SUMMARY:** _Helpful links to documentation_
      ### ðŸ”Ž Supporting resources:
      - USWDS Docs: [USWDS Documentation](https://designsystem.digital.gov/)
      - VADS Docs: [VADS Experience Standards](https://design.va.gov/components/)
      - VADS Docs: [VADS Components Documentation](https://design.va.gov/components/)
      - VADS Docs: [VADS Components Storybook](https://design.va.gov/storybook/?path=/docs/about-introduction--docs)
      - VA Platform Docs: [Accessibility defect severity rubric](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric)
      - VA Github Docs: [List of common issue tickets](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/accessibility/common-issues) you can reference, copy, and add to.
      - W3C Docs: [Web Content Accessibility Guidelines (WCAG) 2.2](https://www.w3.org/TR/WCAG22/)
      - W3C Docs: [WCAG 2.2 Understanding Docs](https://www.w3.org/WAI/WCAG22/Understanding/)
