name: OCTO-DE Crew Onboarding Checklist
description: Onboard a member of OCTO to a Digital Experience Crew
title: "[OCTO-DE Crew Onboarding]: "
labels: ["onboarding"]
body:
- type: markdown
  attributes:
    value: |
      This issue is for onboarding a member of OCTO to a Digital Experience Crew. Please assign to the Crew lead after opening.
- type: dropdown
  id: crew_name
  attributes:
    label: What OCTO-DE Crew is the team member joining?
    multiple: false
    options:
      - Account Experience
      - Benefits
      - Health
      - Mobile
      - Platform
      - Sitewide
- type: dropdown
  id: cop_name
  attributes:
    label: What OCTO Community of Practice is the team member part of?
    multiple: false
    options:
      - Design
      - Engineering
      - Product
- type: checkboxes
  attributes:
    label: Has user received VA.gov email address?
    description: User must have @va.gov email address provisioned
    options:
    - label: User has @va.gov email address
- type: input
  id: va_email
  attributes:
    label: VA Email Address
    description: What is the VA email address of the person being onboarded?
    placeholder: 'example@va.gov'
- type: checkboxes
  attributes:
    label: Has user been added to Department of Veterans Affairs Github Organization?
    description: User must be listed in https://github.com/orgs/department-of-veterans-affairs/people
    options:
    - label: User is member of Github org
- type: input
  id: github_username
  attributes:
    label: Github Username
    description: What is the Github username of the person being onboarded?
    placeholder: '@Octocat'
- type: checkboxes
  attributes:
    label: Has user been added to DSVA Slack?
    description: User must be a member of https://dsva.slack.com/
    options:
    - label: User is member of DSVA Slack
- type: input
  id: slack_username
  attributes:
    label: Slack Username
    description: What is the Slack username of the person being onboarded?
    placeholder: '@Slackbot'
- type: checkboxes
  attributes:
    label: Platform Onboarder Tasks
    description: To be performed by Platform team admins
    options:
    - label: "Add to Slack group: @octo-de-platform https://dsva.slack.com/admin/user_groups"
    - label: "Add to Github team: octo-de-platform https://github.com/orgs/department-of-veterans-affairs/teams/octo-de-platform"
    - label: "Post welcome Slack message: #platform-team"
    - label: 'Add to Confluence group "platform-crew-octo-de": https://admin.atlassian.com/s/10f8a514-fd86-4b32-8ba3-c0bfc6969f88/groups/81f1ea1a-fc6d-4b27-aed5-0bb73dd86c02'
    - label: "Update Team Roster: https://vfs.atlassian.net/wiki/spaces/LEAD/overview#OCTO-DE-Leadership (can be seen on https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)"
    - label: "Schedule recurring 1:1"
    - label: "Pagerduty OOB Deploy setup - Admin : https://vfs.atlassian.net/wiki/spaces/ECP/pages/1959165976/Out+of+band+deployment+approval#Admin"
    - label: "Add to VA GOV DEVOPS Service Now group: https://github.com/department-of-veterans-affairs/CTO/discussions/100"
    - label: "Add to MS Teams / Sharepoint group: https://teams.microsoft.com/l/team/19%3aWKiBsscnhmaeQZivkkji2GkkHwY1RNX0AXrCfiJdkwg1%40thread.tacv2/conversations?groupId=1dc3d637-a996-47c3-a0cb-0562475da049&tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf"
- type: checkboxes
  attributes:
    label: Platform Onboardee Tasks
    description: To be performed by new Platform team member
    options:
    - label: "Register for Platform Orientation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D"
    - label: "Schedule PO meetings with teams"
    - label: "Update Slack profile in accordance with: https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile"
    - label: "Pagerduty OOB Deploy setup - User : https://vfs.atlassian.net/wiki/spaces/ECP/pages/1959165976/Out+of+band+deployment+approval#User"
    - label: "Link to Platform team welcome guide: https://vfs.atlassian.net/wiki/spaces/AP/pages/1413808450" 
    - label: "Link to Platform team meetings: https://vfs.atlassian.net/wiki/spaces/AP/pages/2141519911/Platform+Meetings"
