name: "Team offboarding"
description: "This ticket is for team offboarding. Use the [individual offboarding ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?template=offboarding-request.md) to offboard specific team members."
title: "Team offboarding for [Team]"
labels:
  - "offboarding"
  - "team-offboarding"
body:
  - type: markdown
    attributes:
      value: "# Team offboarding" 
  - type: markdown
    attributes:
      value: "## Instructions"
  - type: markdown
    attributes:
      value: |
        Product managers should complete this ticket when a VFS or platform team is offboarding and handing off ownership of its products. 
  - type: markdown
    attributes:
      value: "### Step 1: before you submit this ticket"
  - type: checkboxes
    id: follow-team-offboarding
    attributes:
      label: Complete these steps **before** you complete this ticket.
      description: Review [Team offboarding guidance](https://www.google.com/maps) and [individual offboarding ticket](https://www.google.com/maps)
      options:
        - label: Follow team offboarding guidancelink to platform website page for updating documentation about your team and your products.
          required: true
        - label: Submit an individual offboarding ticket for each team member
          required: true
  - type: markdown
    attributes:
      value: "## Team information"
  - type: markdown
    attributes:
      value: |
        Provide the following information about the team being offboarded: 
  - type: input
    id: team-name
    attributes:
      label: Team name
    validations:
      required: true
  - type: input
    id: last-day
    attributes:
      label: Last day of contract
      description: (MM/DD/YYYY)
    validations:
      required: true
  - type: input
    id: pm-gh
    attributes:
      label: Team Product Manager GitHub handle
    validations:
      required: true
  - type: input
    id: va-po-gh
    attributes:
      label: VA Product Owner GitHub handle
    validations:
      required: true
  - type: input
    id: team-readme-link
    attributes:
      label: Link to your team’s readme or similar document
      description: Link to [team readme](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/health-products/README.md)
    validations:
      required: true
  - type: checkboxes
    id: team-info-up-to-date
    attributes:
      label: Team information must be up top date.
      options:
        - label: My team information document is up to date
          required: true
 
