name: "Team offboarding"
description: "This ticket is for team offboarding. Use the individual offboarding ticket to offboard specific team members."
title: "Team offboarding for [Team]"
labels:
  - "offboarding"
  - "team-offboarding"
body:
  - type: markdown
    attributes:
      value: "# Team offboarding" 
  - type: markdown
    attributes:
      value: "## Instructions"
  - type: markdown
    attributes:
      value: |
        Product managers should complete this ticket when a VFS team is offboarding, after all team and product information has been updated per the [team offboarding guidance](https://www.google.com/maps) and [individual offboarding tickets](https://www.google.com/maps) have been created. 
  - type: markdown
    attributes:
      value: "### Step 1: before you submit this ticket"
  - type: checkboxes
    id: follow-team-offboarding
    attributes:
      label: Complete these steps before you complete this ticket.
      description: Review [team offboarding guidance](https://www.google.com/maps) and [individual offboarding ticket](https://www.google.com/maps)
      options:
        - label: I have updated all my team and product information and provided access per the team offboarding guidance.
          required: true
        - label: I have submitted individual offboarding tickets for each team member.
          required: true
  - type: markdown
    attributes:
      value: "### Step 2: Team information"
  - type: markdown
    attributes:
      value: |
        Provide the following information about the team being offboarded: 
  - type: input
    id: team-name
    attributes:
      label: Team name
    validations:
      required: true
  - type: input
    id: last-day
    attributes:
      label: Last day of contract
      description: (MM/DD/YYYY)
    validations:
      required: true
  - type: input
    id: pm-gh
    attributes:
      label: Team Product Manager GitHub handle
    validations:
      required: true
  - type: input
    id: va-po-gh
    attributes:
      label: VA Product Owner GitHub handle
    validations:
      required: true
  - type: input
    id: team-readme-link
    attributes:
      label: Link to your team’s readme or similar document
      description: Link to [team readme](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/health-products/README.md)
    validations:
      required: true
  - type: checkboxes
    id: team-info-up-to-date
    attributes:
      label: Team information must be up top date.
      options:
        - label: My team information document is up to date
          required: true
  - type: markdown
    attributes:
      value: "### Step 3: Product information"
  - type: markdown
    attributes:
      value: |
        Complete the product information section for each of your team’s products. If you have more products to add, copy/paste to add more sections.
  - type: markdown
    attributes:
      value: "#### Product 1"
  - type: input
    id: product-name-1
    attributes:
      label: Product name
    validations:
      required: true
