name: "Team offboarding"
description: "This ticket is for team offboarding. Use the individual offboarding ticket to offboard specific team members."
title: "Team offboarding for [Team]"
labels:
  - "offboarding"
  - "team-offboarding"
body:
  - type: markdown
    attributes:
      value: "# Team offboarding" 
  - type: markdown
    attributes:
      value: "## Instructions"
  - type: markdown
    attributes:
      value: |
        Product managers should complete this ticket when a VFS or platform team is offboarding and handing off ownership of its products. 
  - type: markdown
    attributes:
      value: "### Before you begin"
  - type: markdown
    attributes:
      value: |
        Complete these steps before you complete this ticket.
  - type: checkboxes
    id: follow-team-offboarding
    attributes:
      label: Complete these steps before you complete this ticket.
      description: [Team offboarding guidance}(https://www.google.com/maps)
      options:
        - label: Follow team offboarding guidancelink to platform website page for updating documentation about your team and your products.
          required: true
        - label: Submit an individual offboarding ticket for each team member
          required: true
 
