name: "Platform Feature Requests"
description: "If you have a request for a feature you believe the VA Platform should implement, complete the information below."
title: "[Feature request name]:"
labels:
  - "platform-feature-request"
assignees:
  - steel36 
  - tayism   
  - twoangstroms 
  - gopixelsgo 
body:
  - type: markdown
    attributes:
      value: |
        If you have a request for a feature you believe the VA Platform should implement, complete the information below. The more information Platform has, the faster we can process the request.
  - type: textarea
    id: topic
    attributes:
      label: Describe the problem
      description: "Describe the problem, and how solving this problem will make things better for VFS Teams, OCTO-DE, VA, or Content Editors"
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Who will benefit 
      description: "How widespread is the problem, i.e. who do you believe would benefit from the Platform solving this problem?"
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: Describe 
    attributes:
      label: Describe your idea
      description: "Describe your Platform feature or service idea, in other words describe how you think the Platform should solve this"
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: evidece
    attributes:
      label: Provide evidence
      description: "Provide the evidence that you have on the need for this enhancement"
      placeholder: 
    validations:
      required: true
  - type: checkboxes
    id: Mission
    attributes:
      label: Platform Mission
      description: Indicate which of the parts of our Platform mission the enhancement would drive (select all that apply)
      options:
        - label: Keeps these products and services available, stable, and secure.
        - label: Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
        - label: Provides shared tools, software, support, and technical infrastructure to accelerate their development.
        - label: Other
  - type: textarea
    id: other-topics
    attributes:
      label: "Other:"
      description: "If 'Other' is selected, please explain here:"
    validations:
      required: false




  
