name: Platform Architecture Working Group
description: Schedule a presentation for the Platform Architecture Working Group
title: "[Platform Arch WG]: "
labels:
  - "platform-architecture-working-group"
  - "Internal Request"
assignees:
  - f1337
  - thepipster
  - td-usds
  - mchelen-gov
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: input
    id: topic
    attributes:
      label: Topic
      description: What is the topic to discuss?
      placeholder: AWS network architecture
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "Please summarize the topic in a few sentences:"
      placeholder: Network path for public requests coming into VAEC AWS cloud environment and the systems and boundaries involved.
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: "What is the status of the documentation?"
      options:
        - "Not Ready"
        - "Draft"
        - "Ready"
    validations:
      required: true
  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: Please link to all documentation that will be covered.
      placeholder: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/TechnicalArchitectureOverview.md
    validations:
      required: false
  - type: textarea
    id: points-of-contact
    attributes:
      label: Points of Contact
      description: "Please list the GitHub handles of the main Point(s)-of-Contact who own the item that will be reviewed:"
      placeholder: "@my-github-handle"
    validations:
      required: false
  - type: checkboxes
    id: ready
    attributes:
      label: Topic
      description: What topics does this presentation include?
      options:
        - label: Frontend application
        - label: Backend application
        - label: Network
        - label: Other
  - type: input
    id: other-topics
    attributes:
      label: "Other:"
      description: "If 'Other' is selected, please list the other topic(s) here:"
    validations:
      required: false