name: Platform Leadership
description: Issues that are being handled by Platform Leadership team.
labels: ["platform-leadership"]
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: Please describe the issue.
      placeholder: Tell us what the issue is!
  - type: textarea
    id: ac
    validations:
      required: true
    attributes:
      label: Acceptance Criteria
      description: How do we know when this goal is complete?
      value: |
         - [ ] Feature A has been deployed in production
         - [ ] Documentation has been updated in Confluence      value: "Let's do a thing!"
  - type: checkboxes
    id: subjects
    validations:
      required: true
    attributes:
      label: Subject Areas
      description: What subject areas apply to this issue?
      options:
        - label: Product
        - label: Design
        - label: Engineering
        - label: OCTO-DE


