name: Public Website Intake Form
description: To file request with Public Websites
title: "PW intake: <Type of Request> from <Team>"
labels: 
  - "Public Websites"
  - "Needs refining"
  - sitewide
assignees: 
  - jilladams
  - FranECross
  
body:
  - type: markdown
    attributes:
      value: |
        If you need engineering support for: 
          - **Redirects of a non-Facility URL** that have **first been vetted by the Platform Product Support team**. Please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
          - **Injected header**: Please submit [Injected Header issue template](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=jilladams&labels=Injected+header%2C+Needs+refining%2C+%E2%AD%90%EF%B8%8F+Public+Websites%2C+VA.gov+frontend&template=injected-header.md&title=Injected+header%2Ffooter%3A+%3Cdomain%28s%29%3E)
          - **REACT sign-in widgets or feature flags** (flipper)
            - **Note:** App team engineers are responsible for flipper implementation related to their products. PW engineers can consult as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/) for more info.
          - **If you have content requests**, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)

          ### Prioritization
          Our team works in 2-week sprints, and new tickets will be refined before being assigned in future sprints. If your request is time-critical, please be clear about user testing / launch schedules in your description. Urgent sprint injections will require approval from PW PO, Dave Conlon.

          # Intake information
  - type: checkboxes
    id: fe-needs
    attributes:
      label: Indicate if you need front-end engineering support for 
      options:
        - label: Content audit
        - label: Implementation of REACT sign-in widgets
        - label: Support for UAT testing or phased roll out of app/tool landing page
        - label: Implementation of Translation widgets
        - label: Something else
  - type: textarea
    id: customer-request
    attributes:
      label: Describe your request
      description: How can Public Websites help you? Describe the tool, feature, or functionality you are working on, and the help you need.
    validations:
      required: true
  - type: textarea
    id: customer-timing
    attributes:
      label: Time constraints / launch deadlines  
      description: Enter "no hard timing" if Public Websites can complete this work per our team's prioritization. Describe any planned launch timing. Link to launch plan, if it exists. Please note anything driving timing, e.g. outside contractors, internal executive deadlines, or whether timing is preferred but can be flexible. 
    validations:
      required: true
  - type: input
    id: customer-slack
    attributes:
      label: Your product/team Slack channel
      description: If your team works in Slack, please note the primary channel for this request
  - type: input
    id: customer-PO
    attributes:
      label: Your OCTODE product owner
      description: Github handle, name
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ----
          ## Additional Stakeholders? 
         Please share info for anyone else involved in review, decision making, or launch for this project, e.g. Product manager, designer(s), front-end engineer(s), etc.

          ## Collateral for Front-end support
          If front-end eng support is needed, provide a link to your spec, and the unique Flipper ID. 
          
  - type: checkboxes
    id: terms
    attributes:
      label: Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams. 
      options:
        - label: I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.
          required: true
  - type: markdown
    attributes:
      value: |
        ----
        ### Public Websites internal use
        #### Acceptance Criteria
        - [ ] Move to va.gov-cms repo
        - [ ] Convert this request into a Zenhub epic or add to existing epic
        - [ ] Follow-up with requester to address any open questions/concerns
        - [ ] Create epic/tickets as needed for the Public Websites team to implement

        #### Definition of Done
        * Request ticket is closed and implementation tickets created as needed
