name: Qualitative Data Request
description: Please use this form to request qualitative (textual) data for tier II/tier III support as well as Medallia User Surveys
title: "Qualitative Data Request"
labels: [ "VSP-contact-center", "cc-data-request" ]
assignees:
    - Kimberley2023-CSM, ATMiddleton, newworld2616, aubreyarcangel
body:
  - type: markdown
  attributes:
    value: |
          ## What this form is for
          The Veteran Support Team is responsible for Tier II/Tier III support as well as Medallia User Surveys (among other things) along with associated and data and reporting. Please use this form to request qualitative (textual) data for either. While we have quantitative data for these services within DOMO, we are only able to share the qualitative data on the network due to PII/PHI concerns. (The shared data may contain PII/PHI information, we are only able to share the qualitative data on the VA network.) Please be sure to use VA.gov email ONLY. 
          
          *Please allow 5 business days for delivery.*
  - type: dropdown
    id: data-request-type
    attributes:
      label: Data Type Requested
      description: For MyVA411 call center support data, select \"Support.\" For Medallia survey data, select \"User Surveys.\"
      options:
        - Support
        - User Surveys
    validations:
      required: true
  - type: dropdown
    id: data-source-type
    attributes:
      label: Data Source Type
      description: For MyVA 411 data, select \"MyVA.411.\" For Medallia data, select \"Medallia.\"
      options:
        - MyVA.411 
        - Medallia
    validations:
      required: true
  - type: input
    id: start-date
    attributes:
      label: Date Range Start
      placeholder: MM-DD-YYYY
    validations:
      required: true
  - type: input
    id: end-date
    attributes:
      label: Date Range End
      placeholder: MM-DD-YYYY
    validations:
      required: true
  - type: input
    id: product-name
    attributes:
      label: Product Name(s)
      description: Please provide the name(s) of your product(s).
      placeholder: Facilities Locator
    validations:
      required: true
  - type: textarea
    id: product-description
    attributes:
      label: Product Description
      description: Please provide a high-level description (one or two sentences) of your product(s).
      placeholder: 
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
          ### Please note:
          
          If you are requesting user surveys, please provide the desired URLs and/or key terms. If you are requesting support issues, please select from <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/va411-categorizarion.md" target="_blank">this list of case categories or types</a> and/or key terms. VA411 issues do not capture URL.
  - type: textarea
    id: product-urls
    attributes:
      label: Survey URL(s), key term(s), case category or type
      description: Please provide the root directory(ies) for your product(s). If you want ONLY the URL listed, please specify. Otherwise, any URLs that live under the path provided will be exported as well. If providing specific terms to search for, please include those terms as well as common alternate spellings.
      placeholder: "URLs: ONLY va.gov/find-locations, everything under and including va.gov/health-care  Terms: facility, facilities, community care provider  (The shared data may contain PII/PHI information, we are only able to share the qualitative data on the VA network, VA.gov email ONLY.)" 
    validations:
      required: true
  - type: dropdown
    id: Sub-URLs
    attributes:  
      label: Sub URLs
      description: Include Sub URLs
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: data-delivery
    attributes:
      label: File Delivery Format
      description: Please specify how you would like your data delivered.
      options:
        - All in one file, on one tab
        - One file, different tab for each term/URL
        - One file for each term/URL
    validations:
      required: true
  - type: dropdown
    id: Word-Cloud
    attributes:  
      label: Word Cloud
      description: Please specify if you would like a Word Cloud included with your results.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: va-email
    attributes:
      label: VA Email Address(es)
      description: Please provide the VA.gov email address(es) you wish to have the data delivered. Data cannot be shared to a non VA.gov email address.
      placeholder: johndoe@va.gov
    validations:
      required: true
      
  - type: textarea
    id: add-assignee-labels
    attributes:
      label: Add Assignee and Labels     
      value: |
          If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
          Please leave this field as is when submitting.
    validations:
      required: false

        
