name: Repository service account request
description: Request an AWS service account that can be used with GitHub 
title: "[AWS/GitHub]: Repository service account for TEAM"
labels: ["infrastructure-request", "aws", "github-actions"]
body:
  - type: markdown
    attributes:
      value: |
        This request is for the creation of an AWS service account that can be used with GitHub by a specific team.
  - type: input
    id: repo-link
    attributes:
      label: Link to GitHub repo
      description: Where is your GitHub application code hosted?
      placeholder: ex. https://github.com/department-of-veterans-affairs/<my-team's-code>
    validations:
      required: false
  - type: markdown
    attributes: 
      value: |
        In order for the Infrastructure Team to add the AWS/GitHub service account credentials to the repo provided above:
        Please grant admin access on the repo to VSP Operations team - @department-of-veterans-affairs/vsp-operations
  - type: input
    id: team-name
    attributes:
      label: Team Name
      description: What is your team's name?
      placeholder: ex. Infrastructure Team
    validations:
      required: false
  - type: input
    id: product-owner
    attributes:
      label: Product Owner
      description: Who is your team's product owner?
      placeholder: ex. Saima Simran
    validations:
      required: false
  - type: input
    id: product-manager
    attributes:
      label: Product Manager
      description: Who is your team's product manager?
      placeholder: ex. Hannah Ilja
    validations:
      required: false
  - type: input
    id: related-issue
    attributes:
      label: Related Issue 
      description: Please share related GitHub issue(s)
      placeholder: ex. "#12345"
    validations:
      required: false
  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria 
      description: _To be completed by the Platform Infrastructure Team._
      options:
        - label: aws_iam_user created
        - label: policy attached to user 
        - label: terraform applied
        - label: AWS API keys created for aws_iam_user
        - label: AWS API keys added to team's repo (specified above)
