name: Request Custom Survey
description: Use this template to request adding a custom Medallia Survey to your product pages
title: "Request Custom Survey"
labels: [ "VSP-contact-center", "cc-survey-request" ]
assignees:
  - ATMiddleton 
body: 
  - type: markdown
    attributes:
      value: |
          ## What this form is for
          Use this template to request adding a custom Medallia Survey to your product pages(s). Standard Feedback and Satisfaction surveys are automatically added to all VA.gov pages (with few exceptions). 
          Learn more about [Medallia](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/medallia)
  - type: dropdown
    id: survey-type-requested
    attributes:
      label: Survey Type Requested
      options:
        - Feedback
        - Satisfaction
    validations:
      required: true
  - type: input
    id: product-name
    attributes:
      label: Product Name(s)
      description: Please provide the name(s) of your product(s).
    validations:
      required: true
  - type: textarea
    id: product-description
    attributes:
      label: Product Description
      description: Please provide a high level description (one or two sentences) of your product(s).
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: product-urls
    attributes:
      label: Product URL(s)
      description: Please provide the root directory(ies) for your product(s)
      placeholder: va.gov/find-locations, va.gov/./locations
    validations:
      required: true
  - type: input
    id: launch-date
    attributes:
      label: Launch Date
      description: Please provide the launch or rollout date of your product(s). If already live, please enter today’s date.
      placeholder: MM-DD-YYYY
    validations:
      required: true
  - type: textarea
    id: custom-questions
    attributes:
      label: Custom Survey Questions
      description: Please enter your question and answer options.
      placeholder: 
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
          ### Follow-up and Timeline
          - We will usually review custom survey requests within a few days of receiving them.
        
