name: SOCKS Access Request
description: To request access to SOCKS
title: SOCKS access for [individual]
labels: ['external-request', 'operations', 'ops-access-request']
body:
  - type: markdown
    attributes:
      value: |
        :wave: **_Instructions_**
        1. Before being granted access, you need to either be listed in [Atlas](https://www.va.gov/atlas/product_directory/team_members) or the [Platform roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster). If your name is not there, start the [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) (specifically, the instructions for new VFS team members). If you're on a Lighthouse team, you might not be in Atlas yet. Check the box below to indicate you're on a LH team.
        2. Change the **Title** to include your name.
        3. Do not remove any labels, however you may add your team label for tracking (eg: `BAH-526`).
        4. Attach a screenshot of your e-App (aka E-QIP) Transmittal Confirmation. If you have not started your a-App process, do NOT put in a request.
        5. When the issue is closed as completed, you can continue with on-boarding setup.

        This issue can also be used to update existing access, including updating ssh-keys or changing the access type group you are in. Please link any prior SOCKS access request tickets.
  - type: input
    id: requestor-name
    attributes:
      label: Your Name
      placeholder: e.g. Jane Doe
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Your Email
      description: Please provide your work email
      placeholder: e.g. jane.doe@company.com
    validations:
      required: true
  - type: input
    id: github_handle
    attributes:
      label: Your GitHub Handle
      description: Please provide your work GitHub username
      placeholder: e.g. janedoe
    validations:
      required: true
  - type: input
    id: role
    attributes:
      label: Your Role and Team
      description: Please provide your role and your team name
      placeholder: e.g. Backend Engineer on VA Mobile
    validations:
      required: true
  - type: input
    attributes:
      label: Product Manager (PM) name and email
      description: Provide the name and email of your Product Manager
    validations:
      required: true
  - type: input
    attributes:
      label: Product Owner (PO) name and email
      description: Provide the name and email of your Product Owner
    validations:
      required: true
  - type: dropdown
    id: access_type
    attributes:
      label: Access Type Requesting
      description: Provide level of access you belive you will need. If you are unsure you can [click here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml) and see what your team members are currently in.
      options:
        - ' '
        - automation
        - automation_external
        - developers
        - drupal_developers
        - platform
        - viewers
        - temp_debug_access
    validations:
      required: true
  - type: textarea
    id: ssh-key
    attributes:
      label: Public SSH Key
      description: If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions
      placeholder: ssh-rsa  AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+ username@mail.com
    validations:
      required: true
  - type: checkboxes
    id: passphraseRequirement
    attributes:
      label: SSH Key Passphrase
      description: See [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases) for how to add a passphrase to an SSH key.
      options:
      - label: Please check this box to confirm that your SSH key has a strong passphrase.
        required: true
  - type: textarea
    attributes:
      label: e-App (aka E-QIP) Transmittal Confirmation
      description: Click the area below to attach a screenshot of your confirmation. Double check there is no sensitive information in the screenshot.
      placeholder: Drag your transmittal confirmation screenshot here
    validations:
      required: true
  - type: checkboxes
    id: lighthouse
    attributes:
      label: Lighthouse?
      options:
      - label: I'm on a Lighthouse team
  - type: markdown
    attributes:
      value: |
        ---
        :heavy_minus_sign::heavy_minus_sign::heavy_minus_sign::heavy_minus_sign: All done! :heavy_minus_sign::heavy_minus_sign::heavy_minus_sign::heavy_minus_sign:
        For AWS access, open an [AWS Access Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=aws-access-request.yml&title=AWS+access+for+%5Bindividual%5D).
        :x: Don't fill out anything below here :x:
  - type: checkboxes
    attributes:
      label: Platform DevOps Support - please verify the following items before merging the SOCKS PR
      description: Don't fill this part out, please
      options:
      - label: "Work email address is listed"
      - label: "Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))"
