
name: Disability Benefits - TEST Bug Template
description: Bug issues for Disability Benefits Team 
labels: ["bug", "disability", "disability-benefits", "needs-refinement"]
projects: 
- department-of-veterans-affairs/1660
type: Task

body:
- type: markdown
  attributes:
    value: |
      Use clear, simple language. If you know how to fix the bug, use action verbs to describe the work.
- type: textarea
  attributes:
    label: Description
    description: Describe the bug details, how to reproduce, dependencies, impact, and open questions.
- type: checkboxes
  attributes:
    label: How severe is the problem? 
    options:
      - label: Critical - A Veteran is blocked or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP.
      - label: Moderate - A Veteran is not blocked, but the happy path is interrupted. Fix after critical bugs.
      - label: Minor - Cosmetic bugs and minor language inconsistencies. Defer to sprint planning.
- type: textarea
  attributes: 
    label: Desired behavior
    description: How should the site function or look?
- type: textarea
  attributes:
    label: Tasks
    description: What are the tasks for this work?
    placeholder: |
      - [ ] Task
      - [ ] Task
      - [ ] Task
- type: textarea
  attributes:
    label: Acceptance Criteria 
    description: What are the acceptable conditions to consider this work complete? 
    placeholder: |
      - [ ] AC
      - [ ] AC
      - [ ] AC
- type: checkboxes
  attributes: 
    label: Definition of Done
    description: General
    options:
      - label: Meets acceptance criteria
      - label: Reviewed and approved by product and/or design
- type: markdown
  attributes:
    value: |
      ### General
      - [ ] Meets acceptance criteria
      - [ ] Reviewed and approved by product and/or design
      
      ### Engineering
      - [ ] All tests pass  
      - [ ] New functionality is covered by unit tests
      - [ ] Logging and monitoring are implemented (if applicable)
      
      ### Code Review & Pull Request
      - [ ] Copilot review completed and feedback addressed  
      - [ ] Internal reviewer approved  
      - [ ] PR includes:
        - [ ] Local testing steps  
        - [ ] Flipper/testing state details (if applicable)  
        - [ ] Author’s proof of submission screenshot  
      - [ ] Reviewer added local proof of submission screenshot  
      - [ ] Code functionality verified on Staging after merge    
- type: checkboxes
  attributes:
    label: Refinement Checklist! 
    description: Make this ticket ready to work
    options: 
      - label: Added description, tasks, and acceptance criteria
      - label: Added estimate
      - label: Labeled with Practice Area (engineer, design, product, data science)
      - label: Labeled with Type and characteristics of the ticket (bug, accessibility, request, discovery, documentation, research, content, ux testing, front-end, back-end, datadog, etc.)
      - label: Added any other relevant labels, team, and priority
      - label: Added an Epic or Super Epic
