name: Vets-api ArgoCD terminal access
description: To request access to vets-api terminal
title: Vets-api terminal access for [individual]
labels: ['external-request', 'platform-tech-team-support', 'ops-access-request']
body:
  - type: markdown
    attributes:
      value: |
        :wave: **_Instructions_**
        1. Before being granted access, the individual for whom access is requested (the 'target individual') must either be listed on the [Platform Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster) or have started your [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) and be listed on the [VFS Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
        2. Change the **Title** to include target individual
        3. Add the label used by the target individual's team (eg: `BAH-526`)
        4. Do not remove any of the existing labels.
        5. Prod access is highly restricted. If you need prod access, add an explanation in "Additional Notes" section.
        6. Validate that your E-QIP process has been started with your Vendor Onboarding Representative (listed below in a dropdown). If you have not started your E-QIP process, do NOT put in a request.
  - type: checkboxes
    attributes:
      label: E-QIP Transmittal Date
      description: Have you started your E-QIP process? If not, do not submit this ticket. Ask your Vendor Onboarding Representative to confirm
      options:
      - label: Check this box if you have an E-QIP transmittal date.
    validations:
      required: true
  - type: input
    id: requestor-name
    attributes:
      label: Your Name
      description: Please provide the name of the target individual
      placeholder: Jane Doe
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Your GitHub handle (terminal access is managed through GitHub)
      description: Please provide the work GitHub handle of the target individual
      placeholder: "@username"
    validations:
      required: true
  - type: input
    id: team-name
    attributes:
      label: Team, Role, and Company of the target individual
      description: Please provide the name of the team, their role on that team, and the name of the company the target individual works for
      placeholder: Team Moose, Antler Development, Alces LLC
    validations:
      required: true
  - type: input
    attributes:
      label: Product Manager (PM) name and email
      description: Provide the name and email of the Product Manager working with the target individual
    validations:
      required: true
  - type: input
    attributes:
      label: Product Owner (PO) name and email
      description: Provide the name and email of the Product Owner for the target individual
    validations:
      required: true
  - type: input
    attributes:
      label: Your dsvagovcloud AWS user name (if applicable)
      description: If you have previously been granted AWS access, list your dsvagovcloud AWS user name
      placeholder: First.Last
  - type: checkboxes
    attributes:
      label: ArgoCD terminal access requested for the following environments
      description: Only choose the environments you NEED. 
      options:
      - label: dev
      - label: staging
      - label: sandbox
      - label: production (if requesting, justify prod access in 'Additional Notes' section)
  - type: dropdown
    id: cor-name
    attributes:
      label: COR Name (leave "None" if you listed an AWS user name above)
      description: The name of the Contracting Officer's Representative (COR) covering the target individual.
      options:
        - Cecila Lee
        - Courtney Bethea
        - Crystal Moultrie
        - Doris Lin
        - Vilay Senthep
        - Eunice Garcia
        - Delano McVay
        - Other - please specify in 'Additional Notes'
  - type: dropdown
    id: vendor
    attributes:
      label: Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)
      description: This is the person from the contracting company responsible for the onboarding process of the target individual.
      options:
        - Oddball - Amber Malcolm
        - Insignia - Kimberly S. Cole
        - Agile Six - Anthony M. Arashiro
        - GovernmentCIO - Kimberly O. West
        - Magnum Opus - Paula G. Mendoza
        - Liberty IT -  Michael G. Lovejoy
        - Accenture Federal Services - Alexa Elliot
        - Other - please specify in 'Additional Notes'
  - type: input
    id: expiration-date
    attributes:
      label: Access Expiration
      description: The requested access will be revoked at the start of this date. Enter a date (and time if applicable) or 'ongoing' for non-expiring access. If ongoing is selected, add a justification for this to the 'Additional Notes' field.
      placeholder: DD-MM-YY
    validations:
      required: true
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Use this section to add notes, such as justification for the access request, COR/VOR information when 'Other' was selected, etc.
      placeholder: I need this access because of <reason>
  - type: markdown
    attributes:
      value: |
        ---
        :heavy_minus_sign::heavy_minus_sign::heavy_minus_sign::heavy_minus_sign: All done! :heavy_minus_sign::heavy_minus_sign::heavy_minus_sign::heavy_minus_sign:
        :x: Don't fill out anything below here :x:
  - type: checkboxes
    attributes:
      label: User must exist in a roster before vets-api terminal access can be granted
      description: Don't fill this part out, please
      options:
      - label: "Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)"
      - label: "Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)"
      - label: "If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)"
      - label: "If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added"
      - label: "If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)"
      - label: "Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)"
