name: Vets-api ArgoCD terminal access
description: To request access to vets-api terminal
title: Vets-api terminal access for [individual]
labels: ['external-request', 'platform-tech-team-support', 'ops-access-request']
body:
  - type: markdown
    attributes:
      value: |
        :warning: **_Prerequisites_**
        1. Before being granted access, the individual for whom access is requested (the "target individual") must either be listed on the [Platform Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster) or have started their [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) and be listed as a team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
        1. The target individual MUST be able to provide proof that their E-QIP questionaire has either been transmitted or been adjudicated with a favorable decision. You'll be required to submit proof below. If you have not started your E-QIP process, do NOT submit this ticket. Ask your Vendor Onboarding Representative to confirm (listed below in a dropdown).

        :wave: **_Instructions_**
        1. Change the **Title** to include target individual
        1. Add the label used by the target individual's team (eg: `BAH-526`)
        1. Do not remove any of the existing labels.
        1. Complete required fields and select environments you need access to.
        1. Use the "Additional Notes" section to provide proof of E-QIP transmittal/adjudication.
        1. Prod access is highly restricted. If you need prod access, add an explanation in "Additional Notes" section.
  - type: input
    id: requestor-name
    attributes:
      label: Your Name
      description: Please provide the name of the target individual
      placeholder: Jane Doe
    validations:
      required: true
  - type: input
    id: gh-handle
    attributes:
      label: Your GitHub handle (terminal access is managed through GitHub)
      description: Please provide the work GitHub handle of the target individual
      placeholder: "@username"
    validations:
      required: true
  - type: input
    id: aws-username
    attributes:
      label: Your dsvagovcloud AWS user name (if applicable)
      description: If you have previously been granted AWS access, list your dsvagovcloud AWS user name
      placeholder: First.Last
  - type: input
    id: team-name
    attributes:
      label: Team, Role, and Company of the target individual
      description: Please provide the name of the team, their role on that team, and the name of the company the target individual works for
      placeholder: Team Moose, Antler Development, Alces LLC
    validations:
      required: true
  - type: input
    attributes:
      label: Product Manager (PM) name and email
      description: Provide the name and email of the Product Manager working with the target individual
    validations:
      required: true
  - type: input
    attributes:
      label: Product Owner (PO) name and email
      description: Provide the name and email of the Product Owner for the target individual
    validations:
      required: true
  - type: dropdown
    id: cor-name
    attributes:
      label: COR Name (leave "None" if you listed an AWS user name above)
      description: The name of the Contracting Officer's Representative (COR) covering the target individual.
      options:
        - Cecila Lee
        - Courtney Bethea
        - Crystal Moultrie
        - Doris Lin
        - Vilay Senthep
        - Eunice Garcia
        - Delano McVay
        - Jennifer O'Day
        - Laurene "Reney" Cook
        - Rolanda Copeland
        - Other - please specify in 'Additional Notes'
  - type: dropdown
    id: vendor
    attributes:
      label: Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)
      description: This is the person from the contracting company responsible for the onboarding process of the target individual.
      options:
        - Oddball - Amber Malcolm
        - Insignia - Kimberly S. Cole
        - Agile Six - Anthony M. Arashiro
        - GovernmentCIO - Kimberly O. West
        - Magnum Opus - Paula G. Mendoza
        - Liberty IT -  Michael G. Lovejoy
        - Accenture Federal Services - Alexa Elliot
        - Coforma - Jeff Langworthy
        - Other - please specify in 'Additional Notes'
  - type: checkboxes
    attributes:
      label: Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster
      description: If you are on neither, please refer to the **Prerequisites** section at the top, and close this request until complete
      options:
        - label: "[Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)"
        - label: "[Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)"
  - type: checkboxes
    attributes:
      label: Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.
      description: If you have not submitted your survey, do not submit this ticket. Ask your Vendor Onboarding Representative to confirm
      options:
        - label: I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)
          required: true
  - type: checkboxes
    attributes:
      label: ArgoCD terminal access requested for the following environments
      description: Only choose the environments you NEED.
      options:
        - label: dev
        - label: staging
        - label: sandbox
        - label: production (if requesting, justify prod access in 'Additional Notes' section)
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Use this section to add notes, such as justification for the access request, COR/VOR information when 'Other' was selected, E-QIP screenshot/link to other request, etc.
      placeholder: I need this access because of <reason>
  - type: markdown
    attributes:
      value: |
        ---
        :heavy_minus_sign::heavy_minus_sign::heavy_minus_sign::heavy_minus_sign: All done! :heavy_minus_sign::heavy_minus_sign::heavy_minus_sign::heavy_minus_sign:
  - type: checkboxes
    attributes:
      label: Additional resources for Support Engineer
      description: Don't fill this part out, please
      options:
      - label: "For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)"
      - label: "Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only"
