# 2025-10 Explore disability claim decision review options Research Findings

Office of the CTO - Digital Experience (OCTO-DE), Explore disability claim decision review options, Decision Reviews Team

Date: Nov 18, 2025

Contacts: Kyra Berman-Gestring, Lauren Dawson

Research Readout (PDF in progress)

Jump to:

-   [Hypotheses and conclusions](#Hypotheses-and-conclusions)
    
-   [Key findings](#Key-findings)
    
-   [Recommendations](#Recommendations)
    
-   [Next Steps](#Next-Steps)
    
-   [Further research needed](#Further-research-needed)
    
-   [Appendix](#Appendix)
    
-   [Research participants](#Research-participants)

## Veteran Journey

Based on [VA’s Veteran’s Journey](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/va-product-journey-maps/Veteran%20Journey%20Map.pdf), this work fits into the:

-   “Taking care of myself” stage of the [Veteran Journey](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/va-product-journey-maps/Veteran%20Journey%20Map.pdf), and within that stage, the “Managing primary care and chronic health issues” phase
    
-   “Putting down roots” stage, and within that stage, the “Engaging VA to access benefits and services” phase
    
-   “Retiring” stage, and within that stage, the “Finding additional sources of incomes” phase
    

 

## Research Goals

1.  Usability of flow: To evaluate the usability of the guide, “Explore disability claim decision review options” screen flow.
    
2.  Clarity of content: To evaluate participant’s comprehension of the questions and helpfulness of the explanatory content.
    
3.  Effectiveness of guide: To assess participant’s satisfaction with the guide and their confidence in selecting a decision review pathway.
    



## Research Questions

#### Goal 1: Usability of flow

To evaluate the usability of the guide, “Explore disability claim decision review options” screen flow:

-   Do participants understand what the outcomes of using the tool will be before they start?
    
-   Does the number of questions and amount of content in the guide feel manageable?
    

  

#### Goal 2: Clarity of content

To evaluate participant’s comprehension of the questions and helpfulness of the explanatory content:

-   What do participants learn while using the tool?
    
-   Are there questions or text that cause confusion or erroneous responses?
    
-   Where do participants hesitate, backtrack, or request clarification?
    

  

#### Goal 3: Effectiveness of summary screens

To assess participant’s satisfaction with the summary screen and how this screen impacts their confidence in selecting a decision review pathway:

-   What information do participants wish they knew even after getting results from the tool?
    
-   What do participants think they would do next / with the results?
    
-   How confident are participants in the results information?
    
-   Do participants understand what the available decision review options are and the reasons behind them?
    
 

## Methodology

We conducted 7, 60-minute usability test sessions of the “Explore disability claim decision review options” guide, using a coded prototype in the Staging environment on [VA.gov](http://va.gov). These sessions were remote, moderated, evaluative, mixed methods via Zoom and ran from October 6 through October 10, 2025. Each session began with a semi-structured interview to gauge Veterans’ prior understanding of the decision review (DR) options and processes. Participants were asked to use information about their personal situation when completing tasks. The sessions ended with a reflection discussion to assess the impact of the guide on the Veterans’ experience and understanding of decision review options available to them.

## Hypotheses and Conclusions

| Goal | Hypothesis | Conclusion |
|:--------| :-------------| :-------------|
| 1 | Participants will understand that the output of the flow is a tailored summary of options based on their personal circumstance. | **Maybe True** - Participants had mixed expectations of the guide, with 3 participants expecting to get information on options specific to their situation, and 2 participants expecting the guide to provide general information on decision review options. |
  | 2, 1 | Participants understand they can use this tool for both planning and action. | **Definitely True** - 5 of 5 participants said that they would use the guide to both plan next steps and to start the process of a decision review. 5 of 7 participants would use this guide in the future and 6 of 7 would recommend it to a friend. Participants also stated that they would use this guide to check on law and policy updates to their claims or if they were denied. |
| 1,2 | There may be some confusion around what types of claims (disability vs. non-disability) can leverage this guide. | **Definitely True** - When participants were asked: “What types of claims do you think this guide supports?”, 2 participants believed the guide was to support denied claims and 2 understood the guide to support disability claims. The remaining 3 participants were confused, answering: “benefits”, “all of them”, and “supplemental, higher level review, board appeal”. |
| 1, 2 | Participants will be able to move through every question and arrive at the appropriate summary screen, without assistance.| **Definitely False** - Launching the guide was not intuitive for participants. 5 out of 7 participants failed Task 1, and were unable to start the guide without moderator support.  Despite this difficulty, 6 of 7 participants passed Task 2, answering all questions in flow without moderator support. Participants found the tasks easy to complete and that completing the guide was not mentally taxing. The structure of the yes/no radio buttons supported participants in completing the guide unassisted. Participants thought the length of the guide to be “about right.” |
| 2, 3 | The guide will support participants learning of the different decision review pathways, and the unique requirements of each. | **Maybe True** - Participants were asked how well they felt they understood the decision review options and which one applies to them, both before and after using the guide. Participants scores improved afterwards: Before using the guide, the average score was 2.57 “Understand a little” out of 4, and after using the guide, the score improved to 3.33 “Understand well” out of 4. 4 out of 7 were able to successfully select a decision review option they were eligible for from the summary screen. Of 4 participants who were asked how they would describe which options may or may not be a good fit for them to a friend, 2 participants were able to clearly state reasons and 2 participants were not. When reviewing options on the summary screen, some participants wanted more information, specifically why someone may choose one option over another, or what the potential cons of a pathway may be.  |
| 2 | The questions and helper text will support users in confidently and correctly selecting an answer. | **Likely False** - There was mixed comprehension throughout the participants’ use of the guide and review of the summary screens which impacted accurate completion of the questions in the guide. When completing the guide, confusion observed included:  There were confusions when participants were trying to ask questions when they had multiple prior claims and conditions. They also expressed confusion around understanding the differences between initial claims, supplemental claims and claims for increase. There was also confusion on specific pages regarding wording and structure (2.IS.1/1.2.A.1 ("Did we decide that your condition is service connected?") and 2.IS.4/1.2.A.2 ("Do you disagree with any part of our decision?") And question 2.0 (“What type of decision do you want us to review?”) 3 out of 7 participants had difficulty selecting an option; all 3 selected which DR option they wanted to pursue, not answering based on their prior submitted claim. There was also confusion with why initial claim and supplemental claim were combined in one radio button option.There were many incorrect assumptions, mostly about VA appeals requirements and about perceived order of operations/hierarchy among DR pathways. Participants had a mental-model based on their prior understanding and experiences that influenced how they would use the guide and informed their decision.  Despite these pain points, participants reported confidence in the questions and a few specifically relied on hint text: When asked both before and after using the guide,”how well they feel they understand the decision review options, the requirements and which one might apply to their situation”, participants’ scores improved. Participants gave an average score of 3.29, "Confident" when selecting a decision review option from the summary screen. 6 out of 6 participants understood they had not submitted their DR request and that there were still additional steps to complete. |
| 2 | Some VA terminology will be confusing to Veterans (ex. service-connected, contested claim, etc.) | **Definitely True** - When asked what was burdensome or confusing overall, 3 participants expressed confusion with VA vernacular and requirements. 2 participants expressed not understanding the differences between claim types and 1 participant expressed confusion with general terminology. 2 participants expressed not understanding the differences between claim types (initial claims, supplemental claims, and claims for increase). |
| 3 | Participants will understand why certain options are applicable to their situation, and why others are not. | **Maybe True** - 4 of 7 participants selected an option they were eligible for from the summary screen, however, when 4 of 7 participants were asked how they would describe which options may or may not be a fit for them to a friend, 2 participants were able to clearly state reasons and 2 participants were not able to. |
| 3 | Most participants will use the summary screen as a resource to return to later. | **Maybe True** - When asked about next steps they may take at the summary screen: 4 participants would learn more or pause to gather information;2 would seek support, either at DAV or call #800;When asked about printing:2 participants stated that they would print, 3 participants stated they would not. |
| 3 | The tone and language of available decision review options and all other options on the summary screen feel supportive and nonjudgmental.| **Likely True** - On a scale of 1-4, participants gave an average score of 3.43, finding the wording, tone and presentation to be “somewhat supportive”/”very supportive”. 5 of 5 participants asked said the wording and presentation of the options on the summary screen gave them the confidence to move forward with their next step. |
| 3 | Participants will not need additional context beyond the reasons provided on the personalized summary screens. |**Maybe True** - 4 of 7 participants selected a decision review option they were eligible for from the summary screen. Participants self-reported a confidence score of 3.29 (“confident”) in this selection. Despite this confidence, some participants expressed wanting additional information or support. 2 participants expressed wanting to seek support from either the 800 number or the DVA and another participant wanted more explanation about why someone might choose one option over another and what the potential cons could be.  Only 1 participant went through the CFI and disagree path. Although she understood there were two options she expressed confusion on whether or not she could pursue both. 1 participant expressed confusion on why there was differing language of "average time frame" and "timeframe goal". 1 participant specifically did not understand why Board Appeal options all had different time frame goals. When presented with multiple Board Appeal options on the summary screen,1 participant could not identify a difference between Board Appeal Evidence vs. Board Appeal Hearing because all the bullet points were the same. |
| 3 | Participants will consider options from the “Your options” section of the summary screen and not from the “All options” section. |**Likely True** - 4 of 7 participants selected a decision review option they were eligible for from the summary screen. Participants self-reported a confidence score of 3.29 (“confident”) in this selection. 5 of 5 participants asked, reported the wording and presentation of the options on the summary screen gave them the confidence to move forward with their next step. Only 1 participant would pursue an option they are not eligible for. |


## Key Findings

1.  [Launching the guide is not intuitive](#Launching-the-guide-is-not intuitive)
    
2.  [Accordions are drawing focus on the landing page](#Accordions are drawing focus on the landing page)
    
3.  [Veterans would seek support at some point in their DR filing process](#Veterans-would-seek-support-at-some-point-in-their-DR-filing-process)
    
4.  [Veterans are uncertain about VA vernacular and requirements](#Veterans-are-uncertain-about-VA-vernacular-and-requirements)
    
5.  [Most participants would not take immediate action at the summary screen despite high confidence scores in choosing an option and reported trust of information](#Most-participants-would-not-take-immediate-action-at-the-summary-screen-despite-high-confidence-scores-in-choosing-an-option-and-reported-trust-of-information)
    
6.  [Participants often selected an option from the "may be a good fit" options on the summary screen, those who did not expressed preference for human interaction](#Participants-often-selected-an-option-from-the-"may-be-a-good-fit"-options-on-the-summary-screen,-those-who-did-not-expressed-preference-for-human-interaction)
    
7.  [Participants value timeframes when evaluating their Decision Review options, and when they have a choice between options, participants choose the pathway with the shorter timeframe](#Participants-value-timeframes-when-evaluating-their-Decision-Review-options,-and-when-they-have-a-choice-between-options,-participants-choose-the-pathway-with-the-shorter-timeframe)
    
8.  [Participants were confused with specific content and pathway requirements when reviewing options on the summary screen](#Participants-were-confused-with-specific-content-and-pathway-requirements-when-reviewing-options-on-the-summary-screen)
    
9.  [Participants believe there is a specific order and hierarchy among DR pathways](#Participants-believe-there-is-a-specific-order-and-hierarchy-among-DR-pathways)
    
10.  [Participants feel a need to know which decision review pathway they want to pursue before using the guide](#Participants-feel-a-need-to-know-which-decision-review-pathway-they-want-to-pursue-before-using-the-guide)
    


## Details of Findings

Detailed descriptions and supporting evidence for each key finding.

  

#### 1: Launching the guide is not intuitive

Getting started with the guide is not intuitive for participants.The current design uses an action link with text reading “Explore your options”.

-   5 out of 7 participants failed Task 1: Launching the guide without moderator assistance. One participant passed, but launching the guide was not their first action taken

    

> “I don’t expect this [guide] to ask me questions.” - P5
> 
> “What am I going to do now to start?” - P4

  

#### 2: Accordions draw too much focus on the landing page

The primary CTA on the landing page is an action link “Explore your options”, which launches the guide. Participants focus is often directed toward the four accordions beneath the main content, which were included to provide ancillary context for those who may have navigated to the landing page in error. Participants seemed to either be looking for more information, or to expect to launch the guide through the accordions. Those looking for information were seeking information to inform their decision review pathway selection, or were reading new VA terminology and wanted to understand if that information applied to them. Those who were looking in accordions to launch the guide were looking for links to what they thought was most applicable to their situation.

-   5 out of 7 participants engaged with the accordions as a first click on the landing page
    

-   P2 opened "Looking for decision review options for other VA benefits"
    
-   P5 would expand all accordions, and then reviewed information in "Looking for decision review options for other VA benefits"
    
-   P3 opened "Haven't filed a claim yet?"
    
-   When asked how they would get started, P4 said there were 4 different things there, referring to the 4 different accordions as the actionable items.
    
-   P7 opened "Responding to a Statement of the Case (SOC) or Supplemental Statement of the Case (SSOC)?"

    

> “[The accordion] draws my attention and makes me want to open it up to look at everything.” - P5
> 
> “I think my next step would be ‘Looking for decision review options…’ this is where I would expect to find possibly next steps.” - P7

  

#### 3: Veterans would seek support at some point in their decision review filing process

Veterans expressed a preference for human interaction at different points throughout the guide. Some Veterans expressed that they would only navigate a decision review process with the support of a lawyer or Veteran Service Officer (VSO). Others expressed wanting to seek human support when they reached the summary screen, for help in understanding or deciding between options. Another Veteran expressed a preference for decision review pathways that guaranteed a more humanized review, selecting a “may not be a good fit” option on the summary screen in favor of a Board Appeal Hearing because it guaranteed a face-to-face interaction.

-   3 Veterans expressed a preference for filing a Decision Review with assistance from a VSO or attorney.
    
-   2 Veterans would consult community forums or internet search for general information and for input on making a decision on a pathway to pursue.
    
-   3 Veterans would seek human interaction for specific feedback and input on the specifics of their claim through using the 800#, going to the DVA or seeking a DR pathway that guarantees a more personal review of their claim.

    

> “I want a person to talk to. You don’t really know where [the claim]
> goes…but in court, you have to present true statements.’ - P8
> 
> “What applies to me may not apply to someone else, so I’d rather speak to someone and ask these questions…because…these are pretty much cut-dry questions…it would be helpful to be able to talk to someone and explain the specifics as to why I’m trying to do one of the two of the claims.” - P2

  

#### 4: Veterans are uncertain about VA vernacular and requirements

Veterans who are considering a decision review pathway have some familiarity with the processes, requirements, and vernacular of the VA, however there are notable misunderstandings and uncertainties. Veterans expressed uncertainty with general VA terminology as well as confusion between the names and meanings of different claim/appeal types. We also observed that Veterans have preconceived misconceptions about requirements when pursuing VA claim options that can directly impact their trust of the information provided in the guide and selection of an option on the summary screen.

-   3 Veterans directly reported feeling confused by VA terminology.
    
-   4 Veterans had incorrect assumptions about appeals requirements.
    
-   Veterans did not understand the difference between initial vs. supplemental claim and the difference between supplemental claim vs. claim for increase (CFI).
    
-   P1 and P8 incorrectly assumed condition worsening would be submitted using a supplemental claim, when the correct option would be to submit a claim for increase using the 526-EZ.
    
-   P8 incorrectly assumed secondary claims would be submitted through supplemental claims, when they would be submitted using a 526-EZ.
    
-   P8 incorrectly assumed that appeals are only for denied claims, when the options for appeal are actually more broad.
    
-   P8 incorrectly assumed that you need a lawyer to file a Board Appeal request.
    
-   P8 incorrectly assumed Board Appeal and US Court of Appeals were the same.
    

> “I don’t understand the difference between claim for increase and
> supplemental claim.” - P1
> 
> “I had [injury] in service and I had [body part] problems since, and
> my [body part] problem is supplemental to my original injury, so
> that’s what a supplemental claim is, it’s an add on…” - P8

  

#### 5: Most participants would not take immediate action at the summary screen despite reported trust and high confidence scores in choosing an option

The decision review summary screens provide participants with a summary of their options for next steps with direct links to learn more and action links to start a decision review. One participant arrived at a non-decision review summary screen, one arrived at a decision review and claim for increase summary screen, and the remaining 5 participants reached the decision review summary screen applicable to their individual case. 4 out of 7 participants expressed that they would not immediately start a claim from the summary screen, but their next action would be to gather further information. Some participants expressed using the “learn more” links provided on the cards to gather more information about evidence requirements. 2 participants expressed that they would seek further confirmation or support from the VA, by calling the 800# or visiting a DVA office. 2 participants shared that they would print the page for their records, and 1 shared they would take a screen shot to be able to return to the information later.

-   On a scale of 1-4, Veterans gave an average score of 3.29, "Confident", when selecting a decision review option from the summary screen.
    
-   2 Veterans expressed trusting the information because it was on the VA website.
    
-   When asked about next steps they may take at the summary screen:
    

-   5 Veterans would start a claim, with 1 Veteran pursuing an option from "may not be a good fit";
    
-   4 Veterans would learn more or pause to gather information;
    
-   2 would seek support, either at Disabled American Veterans (DAV) or call the VA #800;
    
-   2 Veterans stated that they would print their summary page and 3 Veterans stated they would not print the page.
    

> “I definitely know that I need some supporting documents, so I’d have to get those from my medical records, but, yes, I also have the option to…learn more about evidence needed for a claim for increase.” - P2
> 
> “My next step would be to pause here…I don’t know if I would want to jump into that right now without learning more about the evidence needed.” - P5
> 
> “I would start the claim and at least see what that next page looks
> like and if I felt confident continuing on myself.” - P7

  

#### 6: Participants often selected a Decision Review option they’re eligible for. Those who didn't, expressed preference for human interaction to validate next steps

Decision Review summary screens include cards that reflect pathways the claimant is eligible for based on the answers provided. All additional decision review pathways are represented in cards under a header of “All other decision review options” with bulleted reasons explaining why these other pathways are not eligible options, based on their answers provided. 6 of 7 participants would learn more or pursue an option from options they’re eligible for, 2 of which would seek VA support to review their available options. Only 1 participants expressed wanting to pursue a pathway that they’re not eligible for because of their preference for the human interaction guaranteed in a Board Appeal: Hearing.

-   Task 3: Select an option on the summary screen - 4 out of 7 participants successfully selected an option from the summary screen.
    

-   For the 2 participants who didn't select an option from the summary card, both expressed wanting support through calling the 800# or going to a DVA office;
    
-   1 participants would pursue an option they aren’t eligible for because it guaranteed human interaction through a Board Appeal.
    
-   Only 1 participant out of 7 went through the CFI+ disagree path, and although she understood there were 2 options, she was unclear whether or not she could pursue both.
    


> “I would [choose] Supplemental Claim.” - P3
> 
![enter image description here](https://image2url.com/images/1763480395777-0be0c8c5-dc8c-4f1a-b682-7cfa61fff6fa.png)
*Screenshot of P3's summary screen*  
> 
> “I would do both…the start the supplemental claim and then go back and do the disability compensation if that’s an option.” - P2
>
![enter image description here](https://image2url.com/images/1763480496246-98bb4aed-eac7-4fe6-a710-2508852deff6.png)

*Screenshot of P2's summary screen*  

#### 7: Participants value timeframes when evaluating their Decision Review options. When they have a choice between options, participants choose the pathway with the shorter timeframe

The time it takes to receive a decision varies across each decision review pathway. Average times and timeframe goals are included on each card on the summary screen to give claimants this information upfront when comparing their options. Claimants place high value on understanding the timelines for each pathway and tend to choose the decision review option that offers the shortest time to receive a decision.

-   3 out of 7 participants commented on liking the inclusion of timeframes on the Decision Review Summary screens.
    
-   When participants had multiple DR options on the summary screen, they chose Supplemental Claim and stated their reason was the shorter timeframe.
    

> “[I would] probably [choose] supplemental claim, ‘cause it’s the
> shortest…turnaround time.” - P1
> 
> “I really like that you’d have the timeframes, I think that’s
> helpful.” - P7

  

#### 8: Participants were confused with specific content and pathway requirements when reviewing options on the summary screen

On the summary screens, each decision review option includes a card with bullets providing reasons a claimant is or is not eligible for a pathway based on their answers provided throughout the guide. Despite this summary, participants expressed confusion about specific eligibility reasons and expressed lack of clarity on distinctions between Board Appeal options. Additionally, there was confusion around specific content use and hierarchy of information on the page. Participants expressed mixed perception of a hierarchy among eligible options, mixed understanding that these options were specific to their case and confusion over language differences in timelines between decision review options.

-   Before and after using the guide, participants were asked how well they felt they understood the decision review options, the requirements and which one might apply to their situation. Participants scores improved from before, with an average score of 2.57 out of 4, to 3.33 out of 4 after using the guide.
    
-   Confusion with content:
    

-   When presented with multiple Board Appeal options on the summary screen, P1 could not identify a difference between Board Appeal Evidence vs. Board Appeal Hearing because all the bullet points were the same.
    
-   When asked about the perceived order of the options presented on the summary screen, P2 perceived them as equal while P1 understood them listed in time order. P4 and P7 perceived a hierarchy between the options but unclear what that hierarchy was.
    
-   P1 specifically did not understand why the Board Appeal options all had different time frame goals.
    

-   P1 was confused by the differing use of “average time frame” versus “timeframe goal.”
    
-   Confusion with pathway requirements:
    

-   4 participants were asked how they would describe which options may or may not be a fit for them to a friend; 2 participants were able to clearly state reasons and 2 participants were not.
    
-   When reviewing options on the summary screen, P1 and P2 expressed wanting more information. P1 specified wanting to know why someone may choose one option over another, or what the potential cons of a pathway may be.
    
-   P7 misunderstood the bullets in cards they were not eligible for, thinking that the mention of a year was how long that option would take when it was stating they were ineligible for that option because their claim was decided over a year ago.
    

-   P4 confused the options as restatements of the intro page and did not understand them to be personal to their individual situation.
    
-   2 participants expressed belief that you could not pursue certain decision review pathways on your own, and they required a VSO or attorney to complete.
    

> “Interesting, so the supplemental claim says average time to receive a decision, but then on the Board stuff it says timeframe goal…I like the average time to receive a decision because what does that mean, timeframe goal, like…we hope to get it done by this time, but shrug, we don’t really know?” - P1
> 
> “Previous screen told me what the review options were and this just shows me what they are…I think again and maybe fine tunes it a bit.” - P4
> 
> “They set it up so it’s almost impossible to do without a lawyer.” -P8

  

#### 9: Participants believe there is a specific order and hierarchy among decision review pathways

Claimants may have some prior knowledge or misconceptions about decision review pathways before using the guide. Most participants believe there to be a sequence or hierarchy between decision review pathways, but could not define what pathway comes first before other pathways are attempted. 2 participants had incorrect assumptions about a “final step” in the appeals process, with differing understandings of decision review pathways that could not be appealed.

-   5 participants had incorrect assumptions about perceived order of operations/hierarchy among DR pathways.
    

-   P1, P7 and P8 assumed there was a progression/order of operations or flow from one DR option to another.
    
-   P3 assumed you couldn’t appeal a Higher-Level Review decision.
    
-   P4 assumed you couldn’t appeal a Board Appeal decision.
    

-   P1 expressed wanting to know the progression or hierarchy when reviewing options on the summary screen.
    

> “Well, if I’ve already been given an answer on a Higher-Level…I don’t know where there is to go after that.” -P3
> 
> “I think now since we did the Board Appeal, and I think we did the
> last step in the appeals process, I don’t think there’s any more we
> can do about it.” - P4

  

#### 10: Participants feel a need to know which decision review pathway they want to pursue before using the guide

Prior to engaging with the guide, many Veterans explored the accordions in an attempt to learn more about the DR pathways. This behavior implies they were unaware that the guide’s purpose was to simplify this process and was designed to reduce that burden by helping them identify the right option for their situation. This strong need to know may have caused error or confusion when answering questions in the guide, as 3 of 7 participants responded to questions based on the type of DR they would like to file, not answering based on the decision they received that they disagreed with.

-   4 of 7 participants expressed wanting to know more information to compare decision review options on the landing page, before launching the guide.
    
-   3 of 7 participants (P1, P3 and P4) responded to some questions in the guide based on what claim type they would like to file, not the decision they would like to appeal.
    

> On the intro page, before launching the guide “I’m not sure which one they want me to do.” - P3
> 
> “I guess I have to back up a bit and understand what’s happening here. Am I here because…I’ve already been reviewed and now I want someone else to review the reviewing?” - P1



## Additional Insights

#### Participant sentiments about using the guide

-   Participants found completing the guide to be easy.
    

-   The structure of the yes/no question format made it easier for Veterans to finish the guide on their own, without assistance.
    
-   Veterans found the guide was not mentally taxing to complete.
    
-   Veterans thought the length of the guide to be “about right.”
    

-   Participants prefer links to open in a new tab.
    
-   Participants are comfortable with an unauthenticated experience of the guide.
    
-   Participants would use this guide in the future and recommend it to a friend.
    

-   2 Veterans cited perceived authority as a reason.
    
-   Veterans would use the guide to both plan next steps and to start the process of a decision review.
    
-   Veterans also shared that they would use this guide to check on law and policy updates to their claims or if they were denied.
    

> “It’s user friendly, it’s either a yes or a no.” - P2
> 
> “It’s a great tool, I wish I had it in the past.” - P7

  

#### Discoverability

-   Participants previously learned about Decision Review options through internet (Google) search.
    
-   Participants are interested in where to find the guide sharing ideas: including a link in a decision letter, locating the guide near benefits claim decision, locating on a homepage or through a google search.
    

> “When I googled this information a couple years ago, I felt like it
> directed me more towards VSOs and attorneys than to just get the
> information itself.” - P7

  

#### Understanding the guide is not a form

-   Participants knew this was not a form submitted to the VA.
    

-   6 of 6 participants understood they had not submitted their DR request and that there were still additional steps to complete.
    

> “This is not a form that I would fill out and mail to the VA…but it’s a teaching tool…” - P4

  

#### Difficulty with multiple prior claims

-   Participants found it difficult or confusing to answer questions in the guide when they had multiple prior claims and conditions.
    
-   This may be a challenge unique or overrepresented in the testing environment, as screening questions did not specifically recruit for Veterans who wish to file a decision review.
    

> “My claims were not all approved at the same time, so that’s why I am…not really sure…” - P1

  

## Recommendations

Supporting data for all recommendations is detailed in the Details of Findings and Additional Insights sections.

#### 1. Make starting the guide the clear call to action

Proposed Design Recommendations:

-   Consider changing the "Explore your options" link to a more actionable button.
    
-   Make sure the call to action “Explore your options" is above the fold and visible.
    
-   Consider changing the language on the link to either "Start the guide” or “Understand my options”.
    
-   Possibly add a short one-line explainer above the button: eg: “Answer a few quick questions to find which decision review option fits your situation.”
    
-   Consider using iconography (compass, pathway) to indicate that this is a guided questionnaire not a form.
    
-   Consider a design iteration that includes an overview of decision review pathways in the main content, as Veterans were exploring accordions generally to learn more about the DR pathways before launching the guide.
    

  

#### 2. Deprioritize the accordions on the landing page and streamline the content within

Proposed Design Recommendations:

-   Consider redesign of the Intro page to deprioritize accordions.
    

-   Reduce choices
    

-   Only show 1–2 key accordions “Already filed a claim?” and “Haven’t filed yet?”
    
-   Consider removing "Haven't received a decision yet?" and "Haven't filed a claim yet?" accordions because these use cases are captured in the flow of the guide.
    

-   Move accordions to the summary page. They were distracting from the main goal, which was to start the guide.
    
-   Minimize the visual gravity of the accordions, either through deprioritized design using a line break or other design approach, or consider relocating the information to another page.
    

-   Move the copy "this guide is only for disability compensation decisions. It doesn’t yet support decisions for other benefit types." higher in the Intro page, outside of the accordion.
    
-   Revise the accordion "Looking for decision review options for other VA benefits",
    

-   Focus title and content on other VA Benefit types.
    
-   Remove links to DR options from the body, this is confusing and distracting to Veterans.
    

  

#### 3. Optimize discoverability of the tool

Proposed Design Recommendations:

-   Focus on search engine optimization (SEO) so that Veterans learning about decision reviews can easily find the guide.
    
-   Consider ways to make the guide easily discoverable to Veterans through potentially including a link to the guide in mailed decision letters or locating links near relevant high-traffic areas on the website.
    
-   Consider including a link to the guide with information distributed to Veterans impacted by changes to law or policy, like the PACT ACT.
    
-   Consider adding an "advertisement-style" component block, under the main header of DR pages (supplemental claim, higher level review, board appeal, and choosing a decision review option) to promote use of the guide and to ensure Veterans are using the questionnaire to confirm their eligibility for the DR pathway early and often.
    

-   Example of a proposed user flow:
    

-   Step 1: VA website
    
-   Step 2: Supplemental Claim webpage
    
-   Step 3: "Advertisement for Onramp" (before "On this page" header)
    
-   Step 4: Complete Onramp guide
    
-   Step 5: Confirm appropriate DR option on summary screen
    
-   Step 6: Link on summary screen back to Supplemental Claim webpage
    

-   Relocate "file a supplemental claim" action link" to right below "advertisement for onramp"
    
-   All SC Webpage content just moves underneath.
    

-   Add a short “feel free to come back and use this again later” reminder for when health conditions or policies.
    

  

#### 4. Re-design the introduction page to make the purpose of the guide clear and reduce distraction from main call-to-action (CTA)

Proposed Design Recommendations:

-   Review content to clarify to claimants that this guide will help inform them of their eligible decision review options and that prior knowledge and selection of a pathway is not required.
    
-   Consider deprioritizing bullets of decision review options as this may have reinforced the belief that Veterans need to know which decision review option to select before starting the guide.
    

-   Explore removing altogether or including in a sentence so draw less visual weight.
    

-   Consider including "Before you start" primer that states the situation the user is in...
    

-   eg: 'Have you been denied or received a denial letter for disability benefits from VA? If so, this guide can help you learn what to do next.'
    

-   Clarify the purpose of the guide up front:
    

-   Review content to make it clearer what claim types are supported.
    
-   Add a short “What this guide does” statement at the top of the intro screen.
    

-   Eg. 'This guide helps you understand which decision review options may apply to your situation after a VA disability claim decision.'
    
-   Conversely, add a “What this guide doesn’t do” note 'It won’t submit a claim for you. It will help you know what form to fill out using your own situational information. It helps you learn your options before spending time submitting the wrong form.'
    

-   Consider including a short example scenario to help orient the user to what the guide can help with.
    

-   Eg: 'If you've submitted a claim, and have received a decision that you disagree with, this guide can help you understand and compare your options. It can help you explore the right path for your decision review and help you know which is the right form to submit.'
    

-   Explore ways to distinguish the guide from VA forms the Veteran is familiar with.
    

-   Use a small icon to communicate that this is a guidance tool, not a form submission.
    

-   Ideas: compass or path icon, magnifying glass icon
    

-   Use a button to launch the guide.
    
-   Use a brief title that includes "guide" or "tool".
    
-   Consider using content that is less formal and includes less VA vernacular.
    

-   Consider iterations to the title of the tool/landing page for brevity and to better communicate the expectation of the page.
    

-   Use more actionable language.
    

  

#### 5. Clarify VA Terminology and use more plain language

Proposed Design Recommendations:

-   Add plain-language definitions to each VA term.
    

-   Eg. Initial claim: the first time you applied for this benefit.
    
-   Eg. Supplemental claim: new evidence about a previous claim.
    
-   Eg. Claim for increase: your condition got worse, and you’re asking for a higher rating.
    

  

#### 6. Revise the phrasing of the question and separate options into individual radio buttons on screen 2.0

Proposed Design Recommendations:

-   Rephrase question 2.0 from "What type of decision do you want us to review?" to:
    

-   “Which of these best describes the decision you already received?” or,
    
-   “What kind of claim did the VA already decide?”
    

-   Add additional text to help the user better understand that the question is referring to a claim that was decided in the past.
    
-   Separate the options in the radio buttons so that there is only one type per radio button to avoid confusion.
    

-   Change the  radio buttons to:
    

-   Initial claim: I filed a disability claim for a new condition
    
-   Claim for increase: I filed a disability claim to increase my disability rating for a condition that got worse.
    
-   Supplemental claim with New Evidence: I submitted new evidence after a previous decision.
    
-   Supplemental claim based on change in Law or Policy: I requested a review based on a change in law or policy. (NOTE: This may eliminate questions in the flow)
    
-   Higher-Level Review: A senior reviewer reviewed my previous claim decision.
    
-   Board Appeal decision: A Veterans Law Judge at the Board of Veterans’ Appeals reviewed my case.
    

-   Or change the radio buttons to:
    

-   Initial claim: I filed a disability claim for a new condition
    
-   Claim for increase: I filed a disability claim to increase my disability rating for a condition that got worse.
    
-   Supplemental claim: I submitted new evidence after a previous decision or requested a review based on a change in law or policy.
    
-   Higher-Level Review: A senior reviewer reviewed my previous claim decision.
    
-   Board Appeal decision: A Veterans Law Judge at the Board of Veterans’ Appeals reviewed my case.

    




#### 7. Clarify content to help Veterans understand the questions in the context of multiple prior conditions/claims

Proposed Design Recommendations:

-   Add guidance text: eg: 'If you’ve had more than one claim, answer these questions thinking of the claim you want to review now.' or 'the claim decision you disagree with'.
    
-   Or add examples: eg: 'If you have several disability claims, (1. tinnitus, 2. condition, 3. condition), only answer questions about one of the claims (tinnitus) at a time when answering these questions.
    
-   Consider changing recruitment screener questions for future usability testing to evaluate if this confusion was overrepresented in the testing scenario.
    

-   Add "Do you currently have a decision that you disagree with or are unhappy with?" or "Are you considering pursuing an appeal on a previously filed claim (within the last year)?"
    

  

#### 8. Update specific screen content to clarify confusing elements and better align with established VA processes

Proposed Design Recommendations:

-   Screen 1.2, "Have we sent you a decision on your claim yet?"
    

-   Add content to help users who have had multiple prior claims that were not all decided at the same time.
    

-   Screens 2.IS.1 and 1.2.A.1, "Condition service connected"
    

-   Review content for clarity and opportunities to simplify.
    

-   Screens 2.IS.4 and 1.2.A.2, "Do you disagree with any part of our decision?"
    

-   Add a line break before “You might also disagree with:” for clarity and connection to the bulleted list following.
    
-   Consider removing “You can request a review when your condition gets worse,” as this question focuses on disagreement with decision, and may confuse Veterans.
    
-   Change "You can request a review when your condition gets worse," as you submit a claim for increase through 526EZ, you do not submit a review.
    

  

#### 9. Clearly state the purpose of the summary screen and provide information in the order in which option(s) appear on the page

Proposed Design Changes:

-   Add a short introduction line at the top of the page explaining that 'these options are personalized for your situation, given the responses you provided. You can review and compare before choosing how to move forward.'
    
-   Refine content for transparency about the difference between "average time frame" and "timeframe goal".
    
-   Clearly state the order decision review options are presented. e.g., “Faster options appear first”
    

-   Alternative: add a tooltip: “Why this order?” to explain how options are arranged.
    

-   On summary screens that display both decision review options and claim for increase (CFI) eligibility, consider adding content to emphasize that both options, CFI and a DR option, are allowable and that they do not have to choose between them.
    
-   Revise content on 2.IS.3 to explicitly state 'you are not eligible for a Decision Review at this time, but you are eligible for…'
    

  

#### 10. Make options on the summary screen(s) easier to compare and understand

Proposed Design Changes:

-   Differentiate Board Appeal paths (Evidence, Hearing, Direct Review).
    

-   Consider adding a brief subheading to explain what is unique to this option.
    
-   Consider revising bullet content with unique differences to help with understanding.
    

-   Add a small comparison cue or iconography (e.g., clock for time, person for interaction) to make scanning the page easier.
    
-   Provide a brief summary of the pathway in each card.
    
-   Explore design iterations that may encourage scrolling.
    

-   Consider adding links or page anchors in bullets in the blue summary card at top.
    
-   Consider moving the "print your results" block lower in the page.
    

  

#### 11. Support Veterans who wish to return to the summary screen information for next-steps at a later time

Proposed Design Recommendations:

-   Provide the option to print or save summary as PDF.
    
-   Offer an option to email results to themself or for use with a VSO or attorney.
    
-   Optimize screen for screenshots.
    
-   Review what information is provided in the "Learn more" links on cards to ensure Veterans have an overview of what to expect when pursuing that pathway.
    
-   Include content on how to return to the guide later, although the answers won't be saved.
    

  

## Next Steps

Share findings and recommendations with the Decision Review team.

## Further research needed

Gaps in the current study and areas requiring additional investigation, such as demographics that were not included in this study include:

-   Assistive Technology users
    
-   Veterans who are currently eligible for and are considering a decision review option
    

## Appendix

#### Research documents

-   [Product Outline/Initiative Kickoff](http://products/decision-reviews/research/decision-reviews-onramp-2025/Decision%20Reviews%20Enhanced%20Onramp%20Initiative%20Kickoff.pdf)
    
-   [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/research/decision-reviews-onramp-2025/2025-08%20Decision%20review%20options%20tool%20usability%20evaluation%20Research%20Plan.md)
    
-   [Conversation/Notetaker’s guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/research/decision-reviews-onramp-2025/2025-10%20_Explore%20disability%20claim%20decision%20review%20options_%20Conversation_Notetakers%20Guide.md)
    
-   [Interview transcripts](http://products/decision-reviews/research/decision-reviews-onramp-2025/session-notes)
    

#### Tools used for Synthesis

-   [Observer’s Notetaking Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1757536819851/56cedf13fa8a045f0a38c3c429dc00e2c6dc5dbd?wid=0-1757536962165)
    
-   [Affinity Mapping](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1757536819851/56cedf13fa8a045f0a38c3c429dc00e2c6dc5dbd?wid=0-1760994899625)
    

#### Pages and applications used

-   [Prototype in Staging](https://staging.va.gov/decision-reviews/explore-disability-claim-decision-review-options)
    

  

## Research participants

#### Recruitment criteria

-   Veterans: [9]
    
-   Caregivers: [0]
    
-   Dependents: [0]
    
-   Total: [9]
    
-   Ideal completed sessions: [6]
    

  

#### Primary criteria:

-   50% of participants who have a previous decision review (Preference for disability compensation-related decision review, but not required)
    
-   50% of participants who have worked with a representative or attorney related to claims
    
-   25%-33% of participants who identify as having cognitive difficulty
    
-   Participants from a mix of backgrounds including: service era, device type, and digital literacy.
    

  

#### Secondary criteria:

-   Mix of genders, age, race/ethnicity, and education
    

-   Gender
    

-   At least 3 Veterans who identify as a gender other than male
    

-   Age
    

-   At least 4 55+
    

-   Race/ethnicity
    

-   At least 4 that do not identify as White/Caucasian
    

-   Education
    

-   At least 4 with no degree
    

## Participant Demographics

We talked to 7 total Veteran participants.

  

Audience segment:

-   Veterans: 7 (9 recruited, 1 no show, 1 unused)
    
-   Caregivers: 0
    
-   Family members of a Veteran: 0
    

  

Gender:

-   Male: 5
    
-   Female: 2
    

  

LGBTQ+:

-   Transgender: unknown
    
-   Nonbinary, gender fluid, gender queer, Two-Spirit (Indigenous only), or another gender beyond man or woman: unknown
    
-   Gay, lesbian, or bisexual: unknown
    

  

Devices used during study:

-   Desktop/Laptop: 3
    
-   Tablet: 1, iPad
    
-   Smart phone: 3, 1 Android, 2 iPhones
    
-   Assistive Technology: 0
    

  

Age:

-   25-34: 2
    
-   35-44: 1
    
-   45-54: 1
    
-   55-64: 0
    
-   65+: 3
    

  

Education:

-   High school degree or equivalent: 2
    
-   Some college (no degree): 3
    
-   Associate's degree, trade certificate or vocational training: 1
    
-   Bachelor's degree: 1
    
-   Master's degree: 0
    
-   Doctorate degree: 0
    

  

Geographic location:

-   Urban: 4
    
-   Rural: 3
    

  

Ethnicity:

-   White/Caucasian: 3
    
-   Black/African American: 3
    
-   Hispanic: 0
    
-   Biracial: 1
    
-   Asian: 0
    
-   Native: 0
    

  
  

Disability and Assistive Technology (AT):

-   Cognitive: 2
    
-   AT beginner: 0
    
-   AT advanced user: 0
    
-   Desktop screen reader: 0
    
-   Mobile screen reader: 0
    
-   Magnification/Zoom: 0
    
-   [Speech Input Technology](https://www.w3.org/WAI/perspective-videos/voice/) like Siri/Dragon Naturally Speaking: 0
    
-   Hearing aids: unknown
    
-   Sighted keyboard: unknown
    
-   Captions: unknown
    

  

#### Underserved groups we haven’t talked to

This research does not include the perspectives of the following marginalized Veteran groups:

-   Other than honorable discharge
    
-   Immigrant origin
    
-   Expat (living abroad)
    
-   Identify as (Race): Asian, Native
    
-   LGBTQ+
    
-   AT users (Beginner, Experienced, all AT)



![Table of underserved groups of Veterans showing how many of each were in this study as compared to target numbers. Data available in the table below this image](link - add image to github folder and link here with .png)


##   

## Recruitment of underserved groups in 2025-10 Explore disability claim decision review options Research Study

<img width="795" height="718" alt="image" src="https://github.com/user-attachments/assets/1b69b4ff-3358-4e46-83d0-150a76e02b50" />

**Note:** P6 was a no-show, P9 was cancelled as it was determined that a total of 7 participants was sufficient.

A more accessible version of the table in the above image

| Category | Segment | Target % | Target # | # in Study | Target Achieved? | p1 | p2 | p3 | p4 | p5 | p6 | p7 | p8 | p9 |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| All participants | Total | n/a | n/a | 9 | n/a | n/a | n/a | n/a | n/a | n/a | n/a | n/a | n/a | n/a |
| Assistive Tech (AT) users | Total | n/a | n/a | 0 | n/a | n/a | n/a | n/a | n/a | n/a | n/a | n/a | n/a | n/a |
| No-show participants | Total | n/a | n/a | 2 | n/a | n/a | n/a | n/a | n/a | n/a | n/a | n/a | n/a | n/a |
| Age 55-64+ | General | 50% | 5 | 3 | no | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 1 | N |
| Cognitive Disability | General | 50% | 5 | 2 | no | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 1 | N |
| Mobile user | General | 50% | 5 | 4 | no | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 1 | N |
| Rural | General | 25% | 3 | 3 | yes | 1 | 0 | 0 | 0 | 1 | 0 | 1 | 0 | 0 |
| No degree | General | 25% | 3 | 5 | yes | 0 | 0 | 1 | 1 | 1 | N | 1 | 1 | N |
| Other than honorable | General | 21% | 2 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Immigrant origin | General | 17% | 2 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Women | General | 10% | 1 | 2 | yes | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Expat (living abroad) | General | 0.4% | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Black or African American | Race | 15% | 2 | 3 | yes | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 |
| Hispanic, Latino, or Spanish origin | Race | 12% | 2 | 0 | no | 0 | 0 | 0 | 0 | 0 | N | 0 | 0 | 0 |
| Biracial | Race | 3.9% | 1 | 1 | yes | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |
| Asian | Race | 2.7% | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Native Hawaiian or other Pacific Islander | Race | 0.3% | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| First Nations (Canada) | Race | n/a | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Native, American Indian or Alaska Native | Race | 1.6% | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Gay, lesbian, or bisexual | LGBTQ+ | n/a | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Transgender | LGBTQ+ | n/a | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Nonbinary, gender fluid, gender queer, Two-Spirit (Indigenous only), or another gender beyond man or woman | LGBTQ+ | n/a | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Beginner AT User | AT | 50% | 0 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Experienced AT User | AT | 50% | 0 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Desktop Screen Reader (SR) | AT | 20% | 0 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Mobile Screen Reader (SR) | AT | 20% | 0 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Magnification/Zoom | AT | 20% | 0 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Speech Input Tech (Siri, Dragon) | AT | 20% | 0 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Hearing Aids | AT | 20% | 0 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Sighted Keyboard | AT | 10% | 0 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Captions | AT | n/a | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Switch Device | AT | n/a | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Braille Reader | AT | n/a | 1 | 0 | no | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
