Questions for Veterans

Background
- Could you tell us about your background and military service? *I was 97 Bravo, counter intelegince agent. I was in for 4 years and got sick and got alternate PT test where I could do swimming instead of jogging. My ex-husband and I were on opposite deployment schedules and I was not getting any better physical and they recommended medical termination. My joints would swell, fatigue, migraines, all of that. 
- What has been your experience with using VA benefits? * The process was not great because and it’s still an issue, I was temporarily medically retired because I had an autoimmune disorder and they treated me for Lupus but it doesn’t match all of Lupus. We know you have an autoimmune disorder but what matches the most is Lupus. The only thing they were able to rule out is rheumatoid arthritis. 
At the time, I was still married and I was covered under his Tricare and we divorced after 15 years and I don’t have that rating. I have copies of my medical records but on my DD214 it doesn’t show it and it’s not on my medical rating and I have 75%. 
-How were you notified? *They just sent me a letter that were was going to be a hearing in process. And then they revoked and the person told me the code for the test and it is a diagnosis but no on understands what that is. 
-Did they provide any appeal process? * I don’t remember anything like that. At the time, I had his Tricare and it wasn’t a big concern. 
  - What VA benefits have you used and why? * I got the benefits at the 75% when he left because I knew I would not have benefits. 
I used to work at a Highschool and I couldn’t do it because I was so exhausted and I would get home and sleep for hours and couldn’t get up. I couldn’t do the 9-5 job but I don’t have a choice because I don’t have enough money. 

Transition Experience    
- What was the hardest part of your transition? *The fact that the reason they took the benefit away was because I had no firm diagnosis. You’re taking this away because no one knows what autoimmune disease I had. It wasn’t a doctor that made this decision because they know the code. Not taking consideration that I am always tired, and have swollen joints. Who are they to make the decision because they think this isn’t real. 
- Is there support that you wish you had when you separated from the military? * I think someone fighting in behalf of me would of. She didn’t fight for me. She could have gone to the doctors for me. 
    - If so, what type of support for other aspects of your transition? * I couldn’t use education benefits because I already had a Master's degree when I joined. I was looking into other courses like sign language and I did not want to go back to social work because I knew I would shut down. I worked in a group home/ orphanage prior to joining the military. I  did not want to go back into social work. I wanted to get ACL certified and they would not pay for that. I had to figure it out and pay on my own. It wouldn’t have been much. Not stressful like social work. 

Learning about VA Benefits
- Where did you learn about VA benefits? I was stationed at Fort. Lewis and they did a presentation when you get out. They have a nice VA, near it. I drove over and checked it out. They did a good job of telling me were I needed to go but I didn’t use my benefits, I used his. I went to the Local VA in Florida because that is were I am from. They helped me and walked me through it in the office. I thought they did  a good job with getting out at Fort. Lewis
- VA.gov online experience?  *I don’t enjoy the online VA experience and my job in IT I look for the user experience and bugs. I have noticed it getting better, but I hate it. I noticed you have multiple areas to sign in. I should only have one login instead of multiple websites, like, if I wanted to refill my prescriptions. 
-MyhealtheVet log in? * It’s gotten better, a few years ago there was nothing. Now it’s together except travel vouchers. I should have a tab that says, “ my travel” . For lab and x-ray results, they are not there. Not all the information is uploaded. 
- How was your experience with learning about benefits?
- What would encourage you to learn more about other VA benefits (that you may not be using)? * I use the travel because my Rheumatoid Doctor is an hour away. Every time I have to get reimbursed for gas, I get denied. It’s their doctor and I get denied. They make it were you can’t get reimbursed for gas. 
* My VA is pretty decent. In the beginning it was not good. Then they finally got Doctors. Until Trump took over and I had been on the waiting list and when he acted the VA Choice Act, I was able to get into a local community for pain management and was able to get treated where they burn the pain. Before that I couldn’t get into pain management or even see a Rheumatoid doctor. The waitlist was a year. It’s been much better, that has been within the last 3 years. You couldn’t see a VA specialist unless it was 40 miles radius. The Choice Act, it didn’t matter if there was one within 40 miles. 
- Any other benefits would like to use? *Probably, I don’t know what is all offered, the main thing for me is gas because the nearest VA is two hours away. I had to go to Miami which is four hours away to see a Geneticist and I had to book a hotel and submit a Hotel receipt and they denied it. I ended up paying for the Hotel. They said, I needed to get it pre-approved. 
-Anything that would encourage you to learn more about benefits? *I read the newsletter and I do read that. I get that every month. It’s not that I’m not encouraged, it’s more what I don’t know. Like the State pass and they get you in for free. A lot of times, I’m not eligible for it. That seems to happen every time I look into it. I have given up on that. 
-Would it be helpful if you had a list of benefits? * Yes, that would be great. 
 - If you could wave a magic wand, what you do to make the whole benefits process easier? * I would fix the travel voucher. You can’t send me for somewhere. And the appeal process is a nightmare. If I want to hit the word appeal and type my explanation and submit it. They told me I had to fax something. There is no one that does fax anymore. This was a VA thing. I’ve only been able to do the appeal with a live person, never through the mail. 
- How long did it take to hear back after your submission? *They don’t tell you, you have to go in and check if you got denied or not. You have to randomly check and have to make sure it’s under 30 days. 
