# note: this GHA applies only to Github Projects V2 (Beta)
# docs: https://github.com/actions/add-to-project
name: Add Issues to Github Projects (V2)

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  cop-backend:
    name: Add CoP Backend Issues to Project Board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/department-of-veterans-affairs/projects/815
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          labeled: platform-cop-backend

  platform-leadership:
    name: Add Platform Leadership Issues to Project Board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/department-of-veterans-affairs/projects/623
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          labeled: platform-leadership
