name: Add Issue to Project Board

on:
  issues:
    types: 
    - opened
    - labeled

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Add Platform Support Issues to Project
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/department-of-veterans-affairs/projects/1408
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          labeled: new-vfs-team, new-vfs-team-member, T1-access-request, Offboarding, Platform-Support-Ticket
