name: Assign to Support Project board
# Assigns new issues to project based on label
# See https://github.com/orgs/department-of-veterans-affairs/projects/1408/
# Organizes GitHub issue into respective column based on label

on:
  issues:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign-to-support-project:
    runs-on: ubuntu-latest
    name: Add issues to Github projects based on labels
    steps:
    - name: Add issues to Platform Support Team - Support Tickets
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event.action == 'opened' &&
        contains(github.event.issue.labels.*.name, 'Platform-Support-Ticket')
      with:
        project: 'https://github.com/orgs/department-of-veterans-affairs/projects/1408'
        column_name: 'Support Tickets'
    - name: Add issues with `new-vfs-team` and `new-vfs-team-member` label to Platform Support project Platform Onboarding column
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event.action == 'opened' &&
        (contains(github.event.issue.labels.*.name, 'new-vfs-team-member') ||
        contains(github.event.issue.labels.*.name, 'new-vfs-team'))
      with:
        project: 'https://github.com/orgs/department-of-veterans-affairs/projects/1408'
        column_name: 'Platform Onboarding'
    - name: Add issues with `T1-access-request` label to Platform Support project Access Request column
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event.action == 'opened' && 
        contains(github.event.issue.labels.*.name, 'T1-access-request')
      with:
        project: 'https://github.com/orgs/department-of-veterans-affairs/projects/1408'
        column_name: 'Access Requests'
    - name: Add issues with `Offboarding` label to Platform Support project Access Request column
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event.action == 'opened' && 
        contains(github.event.issue.labels.*.name, 'Offboarding')
      with:
        project: 'https://github.com/orgs/department-of-veterans-affairs/projects/1408'
        column_name: 'Offboarding'
