name: Add Issue to Project Board

on:
  issues:
    types: 
    - opened
    - labeled

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Add Platform Support Issues to Project
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/department-of-veterans-affairs/projects/1408
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          labeled: new-vfs-team, new-vfs-team-member, T1-access-request, Offboarding, Platform-Support-Ticket

  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move Issue to Access Requests Column
        uses: m7kvqbe1/github-action-move-issues@v1.1.2
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          project-url: https://github.com/orgs/department-of-veterans-affairs/projects/1408
          target-labels: T1-access-request
          target-column: Access Requests

      - name: Move Issue to Platform Onboarding Column
        uses: m7kvqbe1/github-action-move-issues@v1.1.2
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          project-url: https://github.com/orgs/department-of-veterans-affairs/projects/1408
          target-labels: new-vfs-team, new-vfs-team-member
          target-column: Platform Onboarding
          
      - name: Move Issue to Offboarding Column
        uses: m7kvqbe1/github-action-move-issues@v1.1.2
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          project-url: https://github.com/orgs/department-of-veterans-affairs/projects/1408
          target-labels: Offboarding
          target-column: Offboarding

      - name: Move Issue to Support Tickets Column
        uses: m7kvqbe1/github-action-move-issues@v1.1.2
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          project-url: https://github.com/orgs/department-of-veterans-affairs/projects/1408
          target-labels: Platform-Support-Ticket
          target-column: Support Tickets

          
