name: Add Issue to Project Board

on:
  issues:
    types: [opened]  # Trigger the workflow when an issue is opened

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Add issue to Support Tickets column
        uses: actions/add-to-project@main
        if: |
          github.event.action == 'opened' &&
          contains(github.event.issue.labels.*.name, 'Platform-Support-Ticket')
        with:
          project: '1408'  # Replace with your actual project ID
          column_name: 'Support Tickets'  # Column name where the issue will be added
          issue: ${{ github.event.issue.number }}  # The issue number to be added to the project
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add issue to Platform Onboarding column
        uses: actions/add-to-project@main
        if: |
          github.event.action == 'opened' &&
          (contains(github.event.issue.labels.*.name, 'new-vfs-team') ||
          contains(github.event.issue.labels.*.name, 'new-vfs-team-member'))
        with:
          project: '1408'
          column_name: 'Platform Onboarding'  # Column name for onboarding tasks
          issue: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add issue to Access Requests column
        uses: actions/add-to-project@main
        if: |
          github.event.action == 'opened' &&
          contains(github.event.issue.labels.*.name, 'T1-access-request')
        with:
          project: '1408'
          column_name: 'Access Requests'  # Column name for access requests
          issue: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add issue to Offboarding column
        uses: actions/add-to-project@main
        if: |
          github.event.action == 'opened' &&
          contains(github.event.issue.labels.*.name, 'Offboarding')
        with:
          project: '1408'
          column_name: 'Offboarding'  # Column name for offboarding tasks
          issue: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
