name: Create Completed Ticket for Colaboration Cycle Touchpoint

on:
  pull_request:

jobs:
  ticket-creation:
    name: Create Completed Ticket
    runs-on: ubuntu-latest
    steps:
      - name: get ticket
        id: get-ticket
        run: |
          response=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/65064 \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json')
          echo "${response}" > ccTicket.json
      
      - name: Create completed ticket
        id: create-completed-ticket
        run: |
          response=$(curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "This is a test",
            "body": "This is a test."
            }' \
          --fail)
          echo "${response}" > response.json

        - name: Close ticket
        run: |
          number=$(cat response.json | jq -r '.number')
          curl --request PATCH \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${$number} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "closed",
            }' \
          --fail
