name: Create Completed Ticket for Colaboration Cycle Touchpoint

on:
  issues:
    types: [labeled]

jobs:
  ticket-creation:
    name: Create Completed Ticket
    runs-on: ubuntu-latest
    steps:
      - name: check for labels
        if: ${{ github.event.label.name == 'staging-review' && contains(github.event.issue.labels.*.name, 'CC-Request')  }}
        run: |
          echo "kickoff label added to cc request ticket"