name: Create Completed Ticket for Colaboration Cycle Touchpoint

on:
  pull_request:

jobs:
  ticket-creation:
    name: Create Completed Ticket
    runs-on: ubuntu-latest
    steps:
      - name: get ticket
        id: get-ticket
        run: |
          response=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/65064 \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json')
          echo "${response}" > response.json
          jq '.number' < response.json

      - name: display response
        run: |
          cat response.json
