name: Create Completed Ticket for Colaboration Cycle Touchpoint

on:
  pull_request:

jobs:
  ticket-creation:
    name: Create Completed Ticket
    runs-on: ubuntu-latest
    steps:
      - name: get ticket
        id: get-ticket
        run: |
          response=$(curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/issues/65064 \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json')
          echo "::set-output name=THE_TICKET::$response"

      - name: check ticket
        run: |
          THE_TICKET="${{ steps.get-ticket.outputs.THE_TICKET }}"
          number=$(echo "$THE_TICKET" | jq '.number')
          echo "Issue Number: $number"
