name: 'Stale Operations Access Requests'
on:
  schedule:
    - cron: '30 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue is stale because there has been 14 days with no activity. Please remove the stale label or comment if you do not wish this issue to be closed in 7 days.'
          days-before-stale: 14
          days-before-close: 7
          days-before-pr-close: -1
          only-labels: 'ops-access-request'
          operations-per-run: 100
          debug-only: true
